add explicit call out about the subtle difference between empty vs omitted
istio/istio.io pull request #10015
Opened 2021-06-29 15:34 UTC by rsalmond

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

At first glance, a quick reading of this example the highlighted description text below appears to contradict it.

![image](https://user-images.githubusercontent.com/4367945/123826489-cfbb8380-d8cd-11eb-85d0-a6f19d8e5e05.png)

This change adds an explicit call out describing the subtle but crucial difference between "omitted" and "empty".

2021-06-29 15:34 UTC, istio-testing commented
Hi @rsalmond. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-06-29 15:38 UTC, craigbox commented
/ok-to-test

I expect this has to be made somewhere different, as it's generated into here?  @ericvn

2021-06-29 15:42 UTC, rsalmond commented
Oh! I should have looked harder, I see it [over here](https://github.com/istio/api/blob/2af152115f81571984b4146e93274f82ecc73f3e/security/v1beta1/authorization_policy.proto#L244-L245). Shall I close this and cut it over there instead?

2021-06-29 17:56 UTC, ericvn requested changes
This PR is trying to change a file which is automatically pulled from another repo. Changes in this file will be reverted on the next automated pull.

The change should be made after the same section here: https://github.com/istio/api/blob/master/security/v1beta1/authorization_policy.proto#L244-L245

The change in that file will be generated into the file pulled into the `master branch here which is reflected in preliminary.istio.io. The istio/api PR can be cherry-picked to the release-1.10 branch and the change will be reflected in istio.io when the next patch release happens.

2021-06-30 01:43 UTC, rsalmond commented
Thanks for the heads up @ericvn, closing in favour of istio/api#2038

2021-06-30 01:43 UTC, closed without merging