Announcing 1.9.7
istio/istio.io pull request #10096
Opened 2021-07-20 22:47 UTC by jacob-delgado

Release notes for 1.9.7.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2021-07-20 22:47 UTC, jacob-delgado commented
/cherry-pick release-1.10

2021-07-20 22:47 UTC, istio-testing commented
@jacob-delgado: once the present PR merges, I will cherry-pick it on top of release-1.10 in a new PR and assign it to you.

<details>

In response to [this](https://github.com/istio/istio.io/pull/10096#issuecomment-883754739):

>/cherry-pick release-1.10


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-07-20 22:58 UTC, istio-testing commented
@jacob-delgado: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | b303b17d406fb2416070a2cbf98a0eafc477802c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/10096/lint_istio.io/1417617647704477696) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-07-21 10:06 UTC, craigbox requested changes

2021-07-21 10:06 UTC, craigbox commented on content/en/news/releases/1.9.x/announcing-1.9.7/index.md
> +- **Fixed** endpointslice creating duplicate IPs on service update.
```suggestion
- **Fixed** `EndpointSlice` races leading to error state. ([Issue 33672](https://github.com/istio/istio/issues/33672))

- **Fixed** `EndpointSlice` creating duplicate IPs on service update.
```

2021-07-21 10:06 UTC, craigbox commented on content/en/news/releases/1.9.x/announcing-1.9.7/index.md
> +- **Added** validator for empty regex match. ([Issue 34065](https://github.com/istio/istio/issues/34065))
Needs "validator" added to .spelling.

2021-07-22 12:22 UTC, craigbox approved these changes

2021-07-22 12:22 UTC, craigbox commented
LGTM, one nit: you set date to 22 July and you say you're going to release on the 23rd.

2021-07-22 13:21 UTC, ericvn requested changes

2021-07-22 13:21 UTC, ericvn commented on content/en/news/releases/1.9.x/announcing-1.9.7/index.md
> +This release note describes what’s different between Istio 1.9.1 and Istio 1.9.2.
This should be 1.9.6 and 1.9.7

2021-07-22 18:02 UTC, jacob-delgado commented on content/en/news/releases/1.9.x/announcing-1.9.7/index.md
> +This release note describes what’s different between Istio 1.9.1 and Istio 1.9.2.
Fixed

2021-07-22 19:02 UTC, ericvn approved these changes

2021-07-22 19:03 UTC, merged

2021-07-22 19:05 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #10105

2021-07-22 19:09 UTC, ericvn commented
> you set date to 22 July

Since it also said Thursday, I suspect they really want it to be the 22nd.