Update index.md
istio/istio.io pull request #10540
Opened 2021-11-25 11:06 UTC by lijiansgit

fix option 2  import error

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2021-11-25 11:06 UTC, istio-testing commented
Hi @lijiansgit. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-25 13:30 UTC, Arhell reviewed
Please sign CLA
https://github.com/istio/istio.io/pull/10540/checks?check_run_id=4322987901

2021-12-08 19:23 UTC, ericvn requested changes
This change should merge into the main branch and then be cherry-picked forward to the release-1.12 branch.

2022-06-27 15:40 UTC, closed without merging

2022-06-28 03:14 UTC, lijiansgit commented
not merged?