zh-translation:zh\docs\tasks\security\authentication
istio/istio.io pull request #10542
Opened 2021-11-27 16:53 UTC by yanrongshi

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2021-11-27 16:54 UTC, istio-testing commented
Hi @yanrongshi. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-11-27 17:29 UTC, Xunzhuo commented
/ok-to-test

2021-11-28 05:16 UTC, yanrongshi commented
> 
Could you merge it for me, please

2021-11-28 05:36 UTC, kebe7jun reviewed
一些 crd 可以不翻译。

2021-11-28 05:36 UTC, kebe7jun commented on content/zh/docs/tasks/security/authentication/jwt-route/index.md
> +注意:该特性只支持 Istio 入口网关，并且需要使用请求身份验证和虚拟
用中文冒号。

2021-11-28 05:36 UTC, kebe7jun commented on content/zh/docs/tasks/security/authentication/jwt-route/index.md
> +* 在一个命名空间中,部署一个 `httpbin` 工作负载，例如 `foo`，
中文符号。

2021-11-28 05:36 UTC, kebe7jun commented on content/zh/docs/tasks/security/authentication/jwt-route/index.md
> +* 移除请求身份认证：
这个可以不翻译。

2021-11-28 08:06 UTC, istio-testing commented
@yanrongshi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 785b15886360dcc768b52d44058ea110fbd93239 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/10542/lint_istio.io/1464867997247082496) | true | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-28 13:36 UTC, Xunzhuo requested changes

2021-11-28 13:36 UTC, Xunzhuo commented on content/zh/docs/tasks/security/authentication/jwt-route/index.md
> +* 使用[Istio 安装指南](/zh/docs/setup/install/istioctl/)安装 Istio。
need a space between zh and en word

2021-11-28 13:36 UTC, Xunzhuo commented on content/zh/docs/tasks/security/authentication/jwt-route/index.md
> +    这个请求身份验证将在 Iitio 网关上启用 JWT 校验，以便验证过的 JWT 声明稍后可以在虚拟服务中用于路由功能。
fix Iitio to Istio

2021-11-28 13:36 UTC, Xunzhuo commented on content/zh/docs/tasks/security/authentication/jwt-route/index.md
> +1. 验证入口网关返回没有 JWT 的 HTTP 404代码：
need a space between number and words

2021-11-28 13:36 UTC, Xunzhuo commented on content/zh/docs/tasks/security/authentication/jwt-route/index.md
> +1. 验证入口网关返回带有无效 JWT 的 HTTP 401代码：
need a space between number and words

2021-11-28 13:36 UTC, Xunzhuo commented on content/zh/docs/tasks/security/authentication/jwt-route/index.md
> +1. 验证入口网关，返回了带有有效 JWT 的 HTTP 404代码，但不包含 `groups: group1` 声明：
need a space between number and words

2021-11-28 13:36 UTC, Xunzhuo commented on content/zh/docs/tasks/security/authentication/jwt-route/index.md
> +* Remove the request authentication:
Need to translate this part into zh

2021-11-29 08:46 UTC, yanrongshi commented
hey,What should I do next？

2021-11-29 09:42 UTC, Xunzhuo commented
> hey,What should I do next？

Fix the issues that reviewers commented on your PR

2021-11-30 02:34 UTC, yanrongshi commented
I have changed it. Please help me check it. Thank you very much

2021-11-30 02:53 UTC, kebe7jun commented on content/zh/docs/tasks/security/authentication/jwt-route/index.md
> +* 在一个命名空间中，部署一个 `httpbin` 工作负载，例如 `foo` ，
```suggestion
* 在 `foo` 命名空间中，部署一个 `httpbin` 工作负载 ，
```

2021-11-30 02:53 UTC, kebe7jun commented on content/zh/docs/tasks/security/authentication/jwt-route/index.md
> +    例如， `"@request.auth.claims.name.givenName"` 匹配嵌套声明 `name` 和 `givenName` 。 使用 `.` 字符作为声明
```suggestion
    例如， `"@request.auth.claims.name.givenName"` 匹配嵌套声明 `name` 和 `givenName` 。 当前不支持使用 `.` 字符作为声明名称。
```

2021-11-30 07:58 UTC, Xunzhuo approved these changes

2021-11-30 08:00 UTC, kebe7jun requested changes

2021-11-30 08:00 UTC, kebe7jun commented on content/zh/docs/tasks/security/authentication/jwt-route/index.md
> +    名称在当前是不被支持的。
```suggestion
```

2021-11-30 08:04 UTC, kebe7jun approved these changes

2021-11-30 08:06 UTC, yanrongshi commented
Thanks for your help ! @Xunzhuo ，@kebe7jun

2021-11-30 08:48 UTC, merged