/zh/news/releases/1.11.x/announcing-1.11.5/index.md
istio/istio.io pull request #10559
Opened 2021-12-04 10:48 UTC by yanrongshi

/zh/news/releases/1.11.x/announcing-1.11.5/index.md

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2021-12-04 10:49 UTC, istio-testing commented
Hi @yanrongshi. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-12-04 15:02 UTC, Arhell reviewed
cc @Xunzhuo

2021-12-04 15:03 UTC, Xunzhuo commented
/ok-to-test

2021-12-04 15:04 UTC, yanrongshi commented
Thanks! @Xunzhuo

2021-12-04 15:44 UTC, Xunzhuo requested changes

2021-12-04 15:44 UTC, Xunzhuo commented on content/zh/news/releases/1.11.x/announcing-1.11.5/index.md
> +- **修复** 修复了 Istio 部署遵循 `values.pilot.nodeSelector` 参数的问题。
Istio -> Istiod

2021-12-04 15:44 UTC, Xunzhuo commented on content/zh/news/releases/1.11.x/announcing-1.11.5/index.md
> +- **修复** 修复了当 Istio 控制平面有活动的代理连接时，集群内的运维人员不能削减资源的问题。
Operator is a concept in Kubernetes, it does not mean `运维人员`, please just keep it.

2021-12-04 15:44 UTC, Xunzhuo commented on content/zh/news/releases/1.11.x/announcing-1.11.5/index.md
> +- **修复** 修复了在 k8s 1.21+ 版本时，工作负载名称标准标签没有正确填充 `CronJob` 的问题。
`metric labels` is better to translate into `监控指标标签` not `标准标签`

2021-12-04 15:52 UTC, Xunzhuo commented on content/zh/news/releases/1.11.x/announcing-1.11.5/index.md
> +- **修复** 修复了通过添加补丁版本来获取释放污点 URL 的问题。
tar URL does not mean `污点 URL`, it is a way to release istio like `https://github.com/istio/istio/releases/download/1.7.0/istio-1.7.0-linux-amd64.tar.gz`, this is a tar URL

2021-12-09 05:59 UTC, yanrongshi commented
@Xunzhuo，Hey, check it out for me，boss

2021-12-17 12:19 UTC, Xunzhuo approved these changes

2021-12-17 12:49 UTC, yanrongshi commented
@Xunzhuo Is this have a  issue? boss

2021-12-17 13:30 UTC, merged