zh/news/releases/1.9.x/announcing-1.9.2/index.md
istio/istio.io pull request #10566
Opened 2021-12-04 14:49 UTC by yanrongshi

zh/news/releases/1.9.x/announcing-1.9.2/index.md

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2021-12-04 14:49 UTC, istio-testing commented
Hi @yanrongshi. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-12-04 15:10 UTC, Xunzhuo commented
/ok-to-test

2021-12-12 15:19 UTC, yanrongshi commented
@Xunzhuo  help to review,boss

2021-12-12 17:55 UTC, Xunzhuo commented
I will reach it out today :)

2021-12-16 04:56 UTC, Xunzhuo requested changes
Small changes, other than LGTM.

2021-12-16 04:56 UTC, Xunzhuo commented on content/zh/news/releases/1.9.x/announcing-1.9.2/index.md
> +- **修复** 修复了一个问题。所以现在在 `EnvoyFilter` 中配置参数时，传输套接字的参数将会被包含在其中。
remove 所以

2021-12-16 04:56 UTC, Xunzhuo commented on content/zh/news/releases/1.9.x/announcing-1.9.2/index.md
> +- **修复** 修正了一个问题，所以现在的 Kubernetes API 服务器默认情况下认为是存在于集群本地内。 这意味着任何试图访问 `kubernetes.default.svc` 的 pod 都
Ditto

2021-12-17 04:44 UTC, Xunzhuo approved these changes
Thanks @yanrongshi

2021-12-17 05:46 UTC, merged