Add Slime to integrations
istio/istio.io pull request #10576
Opened 2021-12-08 10:27 UTC by YonkaFang

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2021-12-08 10:27 UTC, istio-testing commented
Hi @YonkaFang. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-12-08 11:33 UTC, YonkaFang commented
/retest

2021-12-08 11:34 UTC, istio-testing commented
@YonkaFang: Cannot trigger testing until a trusted user reviews the PR and leaves an `/ok-to-test` message.

<details>

In response to [this](https://github.com/istio/istio.io/pull/10576#issuecomment-988733758):

>/retest


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-12-08 11:34 UTC, YonkaFang commented
/check-cla

2021-12-08 13:02 UTC, Arhell reviewed
/ok-to-test

2021-12-09 08:59 UTC, craigbox commented on data/companies.yml
> +      - "Slime is like Slime, it can be any shape you want and you can do anything in it that is good for Istio's ecology."
How about something more like:

```suggestion
    description: "Slime is an intelligent service mesh manager for Istio.
    details:
      - "Slime has a modular architecture that makes it easy to organize and manage various extensions which are focused on enhancing the capabilities and improving the ease of use of Istio."
      - "Using Slime, you can define dynamic service management strategies, which are automatically and conveniently converted to Istio/Envoy configuration."
      - "Just like its namesake, Slime can be any shape you want and it is good for Istio's ecology!"
```

2021-12-09 09:13 UTC, craigbox approved these changes

2021-12-09 09:14 UTC, istio-testing commented
@YonkaFang: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | d05686afa2be07357017184d6608e01dace4642d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/10576/lint_istio.io/1468871289115512832) | true | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-12-09 09:20 UTC, craigbox requested changes

2021-12-09 09:20 UTC, craigbox commented on data/companies.yml
> +    description: "Slime is an intelligent service mesh manager for Istio.
```suggestion
    description: "Slime is an intelligent service mesh manager for Istio."
```

sorry

2021-12-09 09:52 UTC, craigbox approved these changes

2021-12-09 10:28 UTC, merged

2021-12-12 00:16 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #10600