fix: add missing labels in standard metrics
istio/istio.io pull request #10724
Opened 2022-01-05 16:14 UTC by Xunzhuo

Refer to: https://github.com/istio/proxy/blob/master/extensions/common/istio_dimensions.h#L27-L52

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-01-05 22:32 UTC, ericvn commented
Waiting on an approval from @istio/wg-user-experience-maintainers as they own the page.

2022-01-20 22:03 UTC, douglas-reid requested changes
*Downstream IP* is definitely not a standard label for Istio telemetry.

2022-01-20 22:04 UTC, douglas-reid commented
I think this PR is confusion dimensions in stackdriver access logs with dimensions exposed by standard metrics.

2022-01-20 22:15 UTC, douglas-reid commented on content/en/docs/reference/config/metrics/index.md
> +*   **Downstream IP**: This identifies the downstream ip.
```suggestion
```

2022-01-20 22:50 UTC, Xunzhuo commented
Thanks @douglas-reid

2022-01-20 23:06 UTC, douglas-reid approved these changes

2022-01-21 18:56 UTC, merged

2022-01-21 18:59 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #10815