Document EnvoyProxy priorty problem
istio/istio.io pull request #10935
Opened 2022-02-17 16:02 UTC by frankbu

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-02-17 16:13 UTC, istio-testing commented
@frankbu: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | f214f475fa7404636b7dc533e5551052c56d9d13 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/10935/lint_istio.io/1494341684912197632) | true | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-17 16:17 UTC, ericvn commented on content/en/docs/ops/common-problems/network-issues/index.md
> +another filter (e.g., `INSTERT_FIRST`), or set an exlicit priority in the `EnvoyFilter` to override the
```suggestion
another filter (e.g., `INSERT_FIRST`), or set an exlicit priority in the `EnvoyFilter` to override the
```

2022-02-17 16:17 UTC, ericvn commented on content/en/docs/ops/common-problems/network-issues/index.md
> +default creation time-based ordering. For example, adding `priorty: 10` to the above filter will ensure
```suggestion
default creation time-based ordering. For example, adding `priority: 10` to the above filter will ensure
```

2022-02-17 16:27 UTC, istio-testing commented
@frankbu: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | f214f475fa7404636b7dc533e5551052c56d9d13 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/10935/lint_istio.io/1494341684912197632) | true | `/test lint_istio.io`
doc.test.profile_demo_istio.io | f214f475fa7404636b7dc533e5551052c56d9d13 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/10935/doc.test.profile_demo_istio.io/1494341685029638144) | true | `/test doc.test.profile_demo_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-17 18:45 UTC, howardjohn approved these changes

2022-02-17 18:45 UTC, howardjohn commented on content/en/docs/ops/common-problems/network-issues/index.md
> +specific (i.e., they include the `proxyVersion` field in their match criteria) and therefore will be replaced
just a heads up this will change in the future

2022-02-17 20:30 UTC, istio-testing commented
@frankbu: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_default_istio.io | 0d474fb93d3180186bca8d3a5dae71c7856da811 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/10935/doc.test.profile_default_istio.io/1494397127093129216) | true | `/test doc.test.profile_default_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-17 20:55 UTC, frankbu commented
/test doc.test.profile_default_istio.io

2022-02-23 19:40 UTC, craigbox requested changes

2022-02-23 19:40 UTC, craigbox commented on content/en/docs/ops/common-problems/network-issues/index.md
> +## Unchanged envoy filter configuration suddenly stops working
"Envoy filter" or "`EnvoyFilter`"

2022-02-23 20:39 UTC, craigbox approved these changes

2022-02-24 02:02 UTC, frankbu commented
/retest

2022-02-24 02:23 UTC, istio-testing commented
@frankbu: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_demo_istio.io | 3aa73ebbf2ef88aab1f48ea7122feee9e60f5efc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/10935/doc.test.profile_demo_istio.io/1496667007225958400) | true | `/test doc.test.profile_demo_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-24 03:38 UTC, frankbu commented
/test doc.test.profile_demo_istio.io

2022-02-24 05:04 UTC, merged

2022-02-24 05:05 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #10967