[release-1.13] Update istio test reference
istio/istio.io pull request #11061
Opened 2022-03-16 07:15 UTC by zirain

Please provide a description for what this PR is for.

Update istio test reference
this will fix https://github.com/istio/istio.io/pull/11058

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [x] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-03-16 14:03 UTC, ericvn requested changes
So this seems like we will need a version of istio post 1.13.2 (which should be the old test reference). Once a new version of 1.13 is released that supports this, we can merge the original doc and test.

2022-03-17 00:41 UTC, zirain commented
> So this seems like we will need a version of Istio post 1.13.2 (which should be the old test reference). Once a new version of 1.13 is released that supports this, we can merge the original doc and test.

need this commit https://github.com/istio/istio/commit/b70734d0558b13e15879ebb9847e7e9529bcb83a

2022-04-15 22:04 UTC, istio-testing commented
@zirain: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-04-15 23:02 UTC, ericvn commented
This PR can be closed as we have updated the tests to use the 1.13.3 test reference. That PR fixes https://github.com/istio/istio.io/pull/11058 and that PR can be merged once 1.13.3 is live.

2022-04-15 23:02 UTC, closed without merging