hugo update
istio/istio.io pull request #11254
Opened 2022-05-02 17:51 UTC by Arhell

2022-05-02 17:51 UTC, istio-testing commented
Skipping CI for Draft Pull Request.
If you want CI signal for your change, please convert it to an actual PR.
You can still manually trigger a test run with `/test all`

2022-05-02 19:26 UTC, ericvn commented
I did test locally last week with Hugo 0.98.0 and things didn't seem worse. It was part of my testing to see if the blackfriday change was causing an issue on the Ecosystem page, or if was the Hugo update. That issue seems related to changing from blackfriday and not the Hugo release.

2022-05-03 08:05 UTC, Arhell commented
> I did test locally last week with Hugo 0.98.0 and things didn't seem worse. It was part of my testing to see if the blackfriday change was causing an issue on the Ecosystem page, or if was the Hugo update. That issue seems related to changing from blackfriday and not the Hugo release.

This up to date update

2022-05-03 13:08 UTC, ericvn requested changes
Let this sit for a while unless we really need to move up. The 1.14 build-tooling has Hugo 0.97.3 and the main istio.io branch will become the 1.14 branch at 1.14 release so it make sense to leave this at 0.97.3. We can update the main branch build tooling and Hugo here after the release.

2022-07-05 10:48 UTC, closed without merging