Add Cloud Scale Inc as pro services
istio/istio.io pull request #11300
Opened 2022-05-13 04:54 UTC by nandita-cloudscaleinc

Please provide a description for what this PR is for.

Add Cloud Scale® Inc as pro service provider for ISTIO service mesh

And to help us figure out who should review this PR, please put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-05-13 04:54 UTC, istio-testing commented
Hi @nandita-cloudscaleinc. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-05-13 12:58 UTC, ericvn commented
/ok-to-test

2022-05-17 09:31 UTC, nandita-cloudscaleinc commented
Can someone pls review this. Thanks !

2022-05-17 11:18 UTC, craigbox commented
we need to close out https://github.com/istio/istio.io/issues/11240 first I think.

I would also recommend you remove all the "® Inc" (or only include it once) please.

2022-05-17 12:57 UTC, nandita-cloudscaleinc commented
> we need to close out #11240 first I think.
> 
> I would also recommend you remove all the "® Inc" (or only include it once) please.

Thanks Craig. Addressed the comments and kept it only at the required places!

2022-05-24 05:07 UTC, nandita-cloudscaleinc commented
@ericvn can you pls review this request

2022-05-25 04:17 UTC, nandita-cloudscaleinc commented on data/companies.yml
> +      - "Cloud consulting and Istio service mesh experts by Cloud Scale helps in solving all of the needs by selecting the right platforms, cloud solutions and platform needs that integrate smoothly
addressed the review comments. Thanks for the feedback

2022-05-26 04:18 UTC, nandita-cloudscaleinc commented
Can this PR be pls reviewed . Thanks!

cc - @ericvn @craigbox

2022-05-30 11:48 UTC, nandita-cloudscaleinc commented
Gentle Reminder. Can someone pls review this. Thanks

2022-05-30 13:18 UTC, craigbox requested changes

2022-05-30 13:18 UTC, craigbox commented on data/companies.yml
> +    description: "Cloud Scale® Inc experts assess your current applications, runtime deployments, service maps and use-cases, find the right mix of cloud platforms for your workloads, identify gaps i
```suggestion
    description: "Cloud Scale® Inc experts assess your current applications, runtime deployments, service maps and use-cases, find the right mix of cloud platforms for your workloads, identify gaps in technology & skills, and prepare a success plan."
```

I think it's too much longer than the others.  If this LGTM, I can merge.

2022-05-30 16:14 UTC, nandita-cloudscaleinc commented
addressed review comments. Please let me know if there's any other feedback!

2022-05-30 21:57 UTC, craigbox approved these changes

2022-05-30 21:58 UTC, merged