Update index.md
istio/istio.io pull request #11388
Opened 2022-06-08 07:15 UTC by carlo-zhang

The document page should be HTTP instead of http2 and namespace. In the installation document of the new version, the gateways are installed under the istio ingress namespace instead of the istio system.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-06-08 08:02 UTC, zirain requested changes
this is not the right way, I think you should send a PR to master and then cherry-pick to other release branch.
BTW, you also run `make gen && make lint` to pass the CI check, then verify the doc test.

2022-06-08 08:31 UTC, carlo-zhang commented
第一次提交，并不是太懂

2022-06-08 12:28 UTC, craigbox commented
Thank you for your contribution!
This patch is OK; I can take it from this branch to master.

2022-06-08 12:45 UTC, craigbox commented on content/en/docs/setup/getting-started/index.md
> +$ export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http")].port}')
should these two be "istio-ingress" namespace too?

2022-06-09 01:32 UTC, carlo-zhang commented on content/en/docs/setup/getting-started/index.md
> +$ export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http")].port}')
按现在的文档应该是的

2022-06-09 02:54 UTC, zirain commented on content/en/docs/setup/getting-started/index.md
> +$ export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http")].port}')
craig的意思是，如果你把ingressgateway部署在了istio-ingress命名空间中，这条命令里面的istio-system 也需要修改？

2022-06-09 03:01 UTC, zirain commented
通常来说你需要将MR提交给master分支，如果有需要的话，审核人会加上cherry-pick标签，cherry-pick到指定的版本

带有如下标记的页面通常包含有对应的测试脚本保证文档的正确性
![image](https://user-images.githubusercontent.com/4354057/172754544-c5875150-2bd4-4e27-b4aa-704c698c8240.png)

在修改markdown内容后，你需要本地运行 `make gen && make lint`，如果可以的话，保证修改后测试用例通过。
比如本地运行 `TEST_ENV=kind ADDITIONAL_CONTAINER_OPTIONS="--network host" make doc.test.profile_none` 确认是否有错误。

2022-06-21 19:46 UTC, ericvn commented
/ok-to-test

2022-06-21 19:50 UTC, istio-testing commented
@carlo-zhang: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_istio.io_release-1.14 | 5e9cfb21ff92a0a300d792bd535799feb33695c4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11388/gencheck_istio.io_release-1.14/1539334019034910720) | true | `/test gencheck_istio.io_release-1.14`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-08-31 19:10 UTC, ericvn commented
This PR is targeted for the release-1.14 branch which will shortly be archived and likely not archived again. Thus this PR will not show up in the 1.14 version of the documentation. This PR should be rebased on the main branch (and cherry-picked to 1.15 if needed).

2022-11-29 18:49 UTC, ericvn commented
Closing this PR since it's against a branch which doesn't typically see updates. https://github.com/istio/istio.io/pull/12315 may solve this issue as well.

2022-11-29 18:49 UTC, closed without merging