fix 1.13 proxy-config example
istio/istio.io pull request #11485
Opened 2022-06-24 07:46 UTC by yokoyang

The example in [proxy-config](https://istio.io/latest/docs/reference/config/networking/proxy-config/) is invalid. Cause configuration error：

```
error validating data: [ValidationError(ProxyConfig.spec.image): unknown field "type" in io.istio.networking.v1beta1.ProxyConfig.spec.image, ValidationError(ProxyConfig.spec): unknown field "workloadSelector" in io.istio.networking.v1beta1.ProxyConfig.spec]; if you choose to ignore these errors, turn validation off with --validate=false

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-06-24 07:47 UTC, istio-testing commented
Hi @yokoyang. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-06-24 08:47 UTC, Chen-Xintong commented
/ok-to-test

2022-06-24 08:47 UTC, Chen-Xintong commented
@yokoyang Please sign CLA

2022-06-24 09:16 UTC, istio-testing commented
@yokoyang: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_demo_istio.io | 38f392e8138b70c28c73eeb09cf617f07b40bfaa | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11485/doc.test.profile_demo_istio.io/1540255244791844864) | true | `/test doc.test.profile_demo_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-24 09:34 UTC, istio-testing commented
@yokoyang: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_demo_istio.io | 38f392e8138b70c28c73eeb09cf617f07b40bfaa | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11485/doc.test.profile_demo_istio.io/1540255244791844864) | true | `/test doc.test.profile_demo_istio.io`
doc.test.profile_default_istio.io | 38f392e8138b70c28c73eeb09cf617f07b40bfaa | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11485/doc.test.profile_default_istio.io/1540255244758290432) | true | `/test doc.test.profile_default_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-24 11:49 UTC, yokoyang commented
> @yokoyang Please sign CLA

thanks, CLA has added

2022-06-24 13:04 UTC, ericvn commented
/ok-to-test

2022-06-24 14:00 UTC, ericvn requested changes
Updating archive docs is not standard practice. They may get overriden if we ever archived the release again (which can be done) as we will simply replace this with what is in the 1.13 branch. If this change really needs to be made in 1.13 only, and is a change we should get published, the change should be made in the release-13 branch and we should reactive it to the main and 1.14 branches.

That said, should this change also be made in the 1.4 and main branches?

Also, just updating in the archive does not test this change at all against the 1.13 branch and releases.

2022-06-27 01:54 UTC, yokoyang commented
> Updating archive docs is not standard practice. They may get overriden if we ever archived the release again (which can be done) as we will simply replace this with what is in the 1.13 branch. If this change really needs to be made in 1.13 only, and is a change we should get published, the change should be made in the release-13 branch and we should reactive it to the main and 1.14 branches.
> 
> That said, should this change also be made in the 1.4 and main branches?
> 
> Also, just updating in the archive does not test this change at all against the 1.13 branch and releases.

content in  content/en/docs/reference/config/networking/proxy-config/index.html is correct. no need to change.

2022-06-28 13:19 UTC, ericvn commented
> content in content/en/docs/reference/config/networking/proxy-config/index.html is correct. no need to change.

2022-06-28 13:19 UTC, closed without merging