add product security team to approvals
istio/istio.io pull request #11563
Opened 2022-07-11 17:11 UTC by GregHanson

Please provide a description for what this PR is for.

per TOC discussion on July 11, ensure product security members have approval permissions to security releases directory

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-07-11 18:34 UTC, ericvn commented
Greg, as noted in today's TOC call, I'm not sure this is enough. Do you have a better idea on a sample PR that you would've liked to merge? https://github.com/istio/istio.io/pull/11392 is the last on I think.

Looking at those files, we would also have to cover .spelling for the CVE's, content/en/docs/releases/supported-releases/index.md for the table, expand to connect/en/news to cover release notes, and data/args.yml if it affects a patch on the latest release.

2022-07-11 19:23 UTC, ericvn commented
I don't actually recall this being to much of an issue, except maybe the last set (PR noted above) when I was out of country on vacation. Normally, I can cover the document approvals for you. I did think we had identified someone to cover for the last release before I left.

2022-07-12 09:46 UTC, craigbox commented
Could we solve this by making someone on the PSWG a Docs maintainer?
Or, is there any reason that security releases have a different coordination pattern than regular releases? Would we have the same problem there?

2022-07-12 13:36 UTC, ericvn commented
The PSWG does have a communications role IIRC, but I think it did rotate some, so maybe a subset could be added as maintainers. I did notice at least one person on the PSWG list, maybe incorrectly, that also has a lot of authority and could certainly merge PRs if needed. Just another backup plan if a Doc person wasn't contacted beforehand or could't make it at the last minute. 

I know that RMs also have releases (although typically not as important as a potential Day 0 release) and have to work with the Doc team

2022-07-12 14:42 UTC, jacob-delgado commented
Getting docs approval can be difficult just due to the limited number of docs maintainers. Most of the time we've been able to get in contact with Eric, but that can be onerous on him to always be the POC for it on release day. Most of our activities during a release aren't relevant to docs, except for the merging of the PR into the latest release branch.

I'm also fine with us not having anyone on the list as long as there is a github admin we can get in contact with that can do a force merge. I just find it to be a bad practice to do that as we don't want to get into bad habits.

2022-08-03 22:03 UTC, istio-testing commented
@GregHanson: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-01-31 22:35 UTC, istio-testing commented
@GregHanson: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620550813606744064) | true | `/test doc.test.profile_none`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-01-31 22:35 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620550813606744064) | true | `/test doc.test.profile_none`
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620550813640298496) | true | `/test doc.test.multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-01-31 22:36 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620550813606744064) | true | `/test doc.test.profile_none`
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620550813640298496) | true | `/test doc.test.multicluster`
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620550813535440896) | true | `/test doc.test.profile_default`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-01-31 22:36 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620550813606744064) | true | `/test doc.test.profile_none`
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620550813640298496) | true | `/test doc.test.multicluster`
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620550813535440896) | true | `/test doc.test.profile_default`
doc.test.profile_demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_demo_istio.io/1620550813560606720) | true | `/test doc.test.profile_demo`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-01 15:22 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620550813606744064) | true | `/test doc.test.profile_none`
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620550813640298496) | true | `/test doc.test.multicluster`
doc.test.profile_demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_demo_istio.io/1620550813560606720) | true | `/test doc.test.profile_demo`
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620804262114103296) | true | `/test doc.test.profile_default`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-01 15:22 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620550813640298496) | true | `/test doc.test.multicluster`
doc.test.profile_demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_demo_istio.io/1620550813560606720) | true | `/test doc.test.profile_demo`
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620804262114103296) | true | `/test doc.test.profile_default`
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620804262185406464) | true | `/test doc.test.profile_none`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-01 15:22 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620550813640298496) | true | `/test doc.test.multicluster`
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620804262114103296) | true | `/test doc.test.profile_default`
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620804262185406464) | true | `/test doc.test.profile_none`
doc.test.profile_demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_demo_istio.io/1620804262147657728) | true | `/test doc.test.profile_demo`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-01 15:23 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620804262114103296) | true | `/test doc.test.profile_default`
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620804262185406464) | true | `/test doc.test.profile_none`
doc.test.profile_demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_demo_istio.io/1620804262147657728) | true | `/test doc.test.profile_demo`
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620804262218960896) | true | `/test doc.test.multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-01 18:37 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620804262114103296) | true | `/test doc.test.profile_default`
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620804262185406464) | true | `/test doc.test.profile_none`
doc.test.profile_demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_demo_istio.io/1620804262147657728) | true | `/test doc.test.profile_demo`
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620853340256604160) | true | `/test doc.test.multicluster`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-01 18:37 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620804262185406464) | true | `/test doc.test.profile_none`
doc.test.profile_demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_demo_istio.io/1620804262147657728) | true | `/test doc.test.profile_demo`
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620853340256604160) | true | `/test doc.test.multicluster`
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620853340139163648) | true | `/test doc.test.profile_default`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-01 18:37 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620804262185406464) | true | `/test doc.test.profile_none`
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620853340256604160) | true | `/test doc.test.multicluster`
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620853340139163648) | true | `/test doc.test.profile_default`
doc.test.profile_demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_demo_istio.io/1620853340168523776) | true | `/test doc.test.profile_demo`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-01 18:37 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620853340256604160) | true | `/test doc.test.multicluster`
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620853340139163648) | true | `/test doc.test.profile_default`
doc.test.profile_demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_demo_istio.io/1620853340168523776) | true | `/test doc.test.profile_demo`
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620853340214661120) | true | `/test doc.test.profile_none`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-02 17:21 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620853340256604160) | true | `/test doc.test.multicluster`
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620853340139163648) | true | `/test doc.test.profile_default`
doc.test.profile_demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_demo_istio.io/1620853340168523776) | true | `/test doc.test.profile_demo`
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620853340214661120) | true | `/test doc.test.profile_none`
doc.test.profile_minimal_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_minimal_istio.io/1621196621360402432) | true | `/test doc.test.profile_minimal`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-15 17:56 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620853340256604160) | true | `/test doc.test.multicluster`
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620853340139163648) | true | `/test doc.test.profile_default`
doc.test.profile_demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_demo_istio.io/1620853340168523776) | true | `/test doc.test.profile_demo`
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620853340214661120) | true | `/test doc.test.profile_none`
doc.test.profile_minimal_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_minimal_istio.io/1621196621360402432) | true | `/test doc.test.profile_minimal`
doc.test.profile-minimal_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile-minimal_istio.io/1669403343031635968) | true | `/test doc.test.profile-minimal`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-15 17:57 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620853340256604160) | true | `/test doc.test.multicluster`
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620853340139163648) | true | `/test doc.test.profile_default`
doc.test.profile_demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_demo_istio.io/1620853340168523776) | true | `/test doc.test.profile_demo`
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620853340214661120) | true | `/test doc.test.profile_none`
doc.test.profile_minimal_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_minimal_istio.io/1621196621360402432) | true | `/test doc.test.profile_minimal`
doc.test.profile-minimal_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile-minimal_istio.io/1669403343031635968) | true | `/test doc.test.profile-minimal`
doc.test.profile-demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile-demo_istio.io/1669403342935166976) | true | `/test doc.test.profile-demo`
doc.test.profile-default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile-default_istio.io/1669403342872252416) | true | `/test doc.test.profile-default`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-15 17:57 UTC, istio-testing commented
@GregHanson: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.multicluster_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.multicluster_istio.io/1620853340256604160) | true | `/test doc.test.multicluster`
doc.test.profile_default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_default_istio.io/1620853340139163648) | true | `/test doc.test.profile_default`
doc.test.profile_demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_demo_istio.io/1620853340168523776) | true | `/test doc.test.profile_demo`
doc.test.profile_none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_none_istio.io/1620853340214661120) | true | `/test doc.test.profile_none`
doc.test.profile_minimal_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile_minimal_istio.io/1621196621360402432) | true | `/test doc.test.profile_minimal`
doc.test.profile-minimal_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile-minimal_istio.io/1669403343031635968) | true | `/test doc.test.profile-minimal`
doc.test.profile-demo_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile-demo_istio.io/1669403342935166976) | true | `/test doc.test.profile-demo`
doc.test.profile-default_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile-default_istio.io/1669403342872252416) | true | `/test doc.test.profile-default`
doc.test.profile-none_istio.io | f5c4dca822e1a62867a07e895986e6f753b1f942 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11563/doc.test.profile-none_istio.io/1669403342989692928) | true | `/test doc.test.profile-none`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-11-09 01:25 UTC, craigbox requested changes
as a docs maintainer I'm fine with this (we can always tidy up later) due to the timeliness.

We will have to do a bit of rebasing to get this live though...

2023-11-29 16:38 UTC, GregHanson commented
> Looking at those files, we would also have to cover .spelling for the CVE's, content/en/docs/releases/supported-releases/index.md for the table, expand to connect/en/news to cover release notes, and data/args.yml if it affects a patch on the latest release.

closing this one for now.  Adding all the necessary files would result in a lot more GitHub review requests unrelated to just security releases

2023-11-29 16:38 UTC, closed without merging