zh: common-problems/network-issues/index
istio/istio.io pull request #11577
Opened 2022-07-14 01:37 UTC by youhonglian

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-07-14 01:38 UTC, istio-testing commented
@youhonglian: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 3a37558b56f6278f6b4068b364edeea73986dac0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11577/lint_istio.io/1547394762061910016) | true | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-08 23:45 UTC, windsonsea reviewed
Read the build log about indentation error:
```
ERROR 2022/07/14 01:38:16 Text blocks need to not be indented, or indented by a multiple of 4 spaces
```

2022-09-08 23:45 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +假设我们在默认命名空间中也有一个 [sleep]({{< github_tree >}}/samples/sleep) pod `Deployment`。
```suggestion
假设我们在默认命名空间中也有一个 [sleep]({{< github_tree >}}/samples/sleep) Pod `Deployment`。
```

2022-09-08 23:45 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +当使用其 Pod IP 从这个 `sleep` pod 访问 `nginx` 时（这是访问无头服务的常用方法之一），请求通过 `PassthroughCluster` 到达服务器端，但 sidecar 代理打开服务器端无法找到 `nginx` 的路由条目，并且显示 `HTTP 503 UC` 失败。
```suggestion
当使用其 Pod IP 从这个 `sleep` Pod 访问 `nginx` 时（这是访问无头服务的常用方法之一），请求通过 `PassthroughCluster` 到达服务器端，但 sidecar 代理打开服务器端无法找到 `nginx` 的路由条目，并且显示 `HTTP 503 UC` 失败。
```

2022-09-08 23:45 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +  {{< /text >}}
Line 261-267 need to indent 4 spaces.

2022-09-08 23:45 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +1.使用域名代替 Pod IP：
```suggestion
1. 使用域名代替 Pod IP：
```

2022-09-08 23:45 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +  {{< /text >}}
Need indent 4 spaces.

2022-09-13 10:17 UTC, youhonglian commented
@windsonsea fixed

2022-09-13 11:46 UTC, zirain requested changes

2022-09-13 11:46 UTC, zirain commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +
这里是不是漏了一句 `Consider `nginx` is deployed as a `StatefulSet` in the default namespace and a corresponding `Headless Service` is defined as shown below:`

2022-09-13 11:46 UTC, zirain commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +假设我们在默认命名空间中也有一个 [sleep]({{< github_tree >}}/samples/sleep) Pod `Deployment`。
`default` 是k8s的一个命名空间，不能翻译为默认
```console
k get ns
NAME                 STATUS   AGE
default              Active   8h
istio-system         Active   8h
kube-node-lease      Active   8h
kube-public          Active   8h
kube-system          Active   8h
local-path-storage   Active   8h
metallb-system       Active   8h

```

2022-09-13 11:53 UTC, windsonsea reviewed
Need some more revisions, thanks.

2022-09-13 11:53 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +  默认情况下，上面 curl 请求中的 Host 标头将是 Pod IP。在我们对 `nginx` 的请求中将 Host 标头指定为 `nginx.default` 成功返回 `HTTP 200 OK`。
Line 261 also needs to indent 4 spaces

2022-09-13 11:53 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +  这在客户端可能无法在请求中包含标头信息的某些情况下很有用。
Line 271 - 275 also need to indent 4 spaces

2022-09-13 11:53 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +  也可以仅使用域名访问无头服务的特定实例。
Line 290 also needs indent 4 spaces

2022-09-13 11:53 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +  这里的 `web-0` 是 `nginx` 的 3 个副本之一的 pod 名称。
```suggestion
    这里的 `web-0` 是 `nginx` 的 3 个副本之一的 Pod 名称。
```

2022-09-13 11:53 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +有关不同协议的无头服务和流量路由行为的更多信息，请参阅此 [流量路由](/zh/docs/ops/configuration/traffic-management/traffic-routing/)页面。
```suggestion
有关不同协议的无头服务和流量路由行为的更多信息，请参阅此[流量路由](/zh/docs/ops/configuration/traffic-management/traffic-routing/)页面。
```

2022-09-13 11:53 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +当使用其 Pod IP 从这个 `sleep` Pod 访问 `nginx` 时（这是访问无头服务的常用方法之一），请求通过 `PassthroughCluster` 到达服务器端，但 sidecar 代理打开服务器端无法找到 `nginx` 的路由条目，并且显示 `HTTP 503 UC` 失败。
```suggestion
当使用其 Pod IP 从这个 `sleep` Pod 访问 `nginx` 时（这是访问无头服务的常用方法之一），请求通过 `PassthroughCluster` 到达服务器端，
但 Sidecar 代理打开服务器端无法找到 `nginx` 的路由条目，并且显示 `HTTP 503 UC` 失败。
```

2022-09-13 11:53 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +    name: http-web  # Explicitly defining an http port
```suggestion
    name: http-web  # 显式定义一个 http 端口
```

2022-09-13 11:53 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +  clusterIP: None   # Creates a Headless Service
```suggestion
  clusterIP: None   # 创建一个无头服务
```

2022-09-13 11:53 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +假设 Istio 安装了以下配置:
```suggestion
假设安装 Istio 时采用了以下配置：
```

2022-09-13 11:53 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +- `mTLS mode` 设置为 `STRICT`
```suggestion
- 在网格内 `mTLS mode` 设置为 `STRICT`
```

2022-09-13 11:53 UTC, windsonsea commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +服务定义中的 `http-web` 显式指定该端口的 http 协议。
```suggestion
上述 Service 定义中的 `http-web` 显式指定该端口的 http 协议。
```

2022-09-14 02:20 UTC, youhonglian commented
@zirain @windsonsea  fixed

2022-09-14 02:26 UTC, zirain requested changes

2022-09-14 02:26 UTC, zirain commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +当使用其 Pod IP 从这个 `sleep` Pod 访问 `nginx` 时（这是访问无头服务的常用方法之一），请求通过 `PassthroughCluster` 到达服务器端，但 sidecar 代理打开服务器端无法找到 `nginx` 的路由条目，并且显示 `HTTP 503 UC` 失败。
```suggestion
当使用其 Pod IP 从这个 `sleep` Pod 访问 `nginx` 时（这是访问无头服务的常用方法之一），请求通过 `PassthroughCluster` 到达服务器端，但 Sidecar 代理打开服务器端无法找到 `nginx` 的路由条目，并且显示 `HTTP 503 UC` 失败。
```

2022-09-14 02:26 UTC, zirain commented on content/zh/docs/ops/common-problems/network-issues/index.md
> +    这里的 `web-0` 是 `nginx` 的 3 个副本之一的 pod 名称。
```suggestion
    这里的 `web-0` 是 `nginx` 的 3 个副本之一的 Pod 名称。
```

2022-09-14 03:29 UTC, istio-testing commented
@youhonglian: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_default_istio.io | 1ea045c090a4d57cae1a935e4d0c380333706add | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11577/doc.test.profile_default_istio.io/1569872680138575872) | true | `/test doc.test.profile_default`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-19 01:33 UTC, windsonsea commented
/retest

Hi @youhonglian , could you take a look over comments here? Nearly 2 months passed, we look forward to an active movement and communication. If no any response for weeks, it's probable to be closed.

2022-09-22 11:26 UTC, litong01 requested changes
agree with @zirain 's comment, @youhonglian can you take ziran's suggestion so that we can close this one?

2022-10-27 22:03 UTC, istio-testing commented
@youhonglian: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-10-27 22:03 UTC, istio-testing commented
@youhonglian: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-11-03 13:40 UTC, windsonsea commented
Hi @youhonglian, this PR has been opened nearly 4 months. It is time to be closed due to conflicts and no response for a long time.

Feel free to re-open it when you have time to handle it, thanks.

2022-11-03 13:40 UTC, closed without merging