[zh]update  /docs/tasks/extensibility/wasm-module-distribution/index.md
istio/istio.io pull request #11635
Opened 2022-07-24 03:30 UTC by yanrongshi

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-07-24 03:38 UTC, istio-testing commented
@yanrongshi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 2dbfd8a189d1cd2f18a55c6e814950cb60d178ab | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11635/lint_istio.io/1551047145090453504) | true | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-07-24 09:02 UTC, yanrongshi commented on content/zh/boilerplates/trace-generation.md
> +要查看追踪数据，必须向服务发送请求。请求的数量取决于 Istio 的采样率，可以使用 [Telemetry API](/docs/tasks/observability/telemetry/)进行配置。采样率在安装 Istio 时设置，默认采样速率为 1%。在第一个跟踪可见之前，您需要发送至少 100 个请求。
```suggestion
要查看追踪数据，必须向服务发送请求。请求的数量取决于 Istio 的采样率，可以使用 [Telemetry API](/zh/docs/tasks/observability/telemetry/)进行配置。采样率在安装 Istio 时设置，默认采样速率为 1%。在第一个跟踪可见之前，您需要发送至少 100 个请求。
```

2022-07-24 10:17 UTC, istio-testing commented
@yanrongshi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_default_istio.io | d77a05deb2bdcdc7dc02c79d3bcf506823cf5dea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11635/doc.test.profile_default_istio.io/1551130694640472064) | true | `/test doc.test.profile_default_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-07-24 14:13 UTC, yanrongshi commented
/restart

2022-07-24 14:15 UTC, yanrongshi commented
/retest

2022-08-30 14:32 UTC, litong01 requested changes

2022-08-30 14:32 UTC, litong01 commented on content/zh/boilerplates/trace-generation.md
> +要查看追踪数据，必须向服务发送请求。请求的数量取决于 Istio 的采样率，可以使用 [Telemetry API](/zh/docs/tasks/observability/telemetry/)进行配置。采样率在安装 Istio 时设置，默认采样速率为 1%。在第一个跟踪可见之前，您需要发送至少 100 个请求。
I think it maybe better like the following:

请求的数量取决于 Istio 的采样率，采样率可以使用 [Telemetry API](/zh/docs/tasks/observability/telemetry/)进行配置. Istio的默认采样速率为 1%, 如果默认采样率没有改变的话，想要观察到第一个追踪数据，就需要至少发送100个请求。

2022-08-30 14:32 UTC, litong01 commented on content/zh/boilerplates/trace-generation.md
> +$ for i in $(seq 1 100); do curl -s -o /dev/null "http://$GATEWAY_URL/productpage"; done
does this need to be changed?

2022-08-31 15:04 UTC, yanrongshi commented on content/zh/boilerplates/trace-generation.md
> +要查看追踪数据，必须向服务发送请求。请求的数量取决于 Istio 的采样率，可以使用 [Telemetry API](/zh/docs/tasks/observability/telemetry/)进行配置。采样率在安装 Istio 时设置，默认采样速率为 1%。在第一个跟踪可见之前，您需要发送至少 100 个请求。
Thanks

2022-09-08 06:41 UTC, zirain commented
this doc is actually unused
BTW, the title of this PR is wrong.

2022-09-09 02:33 UTC, zirain commented on content/zh/boilerplates/trace-generation.md
> +要查看追踪数据，必须向服务发送请求。请求的数量取决于 Istio 的采样率，可以使用 [Telemetry API](/zh/docs/tasks/observability/telemetry/)进行配置。采样率在安装 Istio 时设置，默认采样速率为 1%。在第一个跟踪可见之前，您需要发送至少 100 个请求。
默认采样速率为 1%。在第一个跟踪可见之前，您需要发送至少 100 个请求。
```suggestion
要查看追踪数据，必须向服务发送请求。请求的数量取决于 Istio 的采样率，可以使用 [Telemetry API](/zh/docs/tasks/observability/telemetry/)进行配置。默认采样速率为 1%。在第一个跟踪可见之前，您需要发送至少 100 个请求。
```

2022-09-09 18:23 UTC, zirain commented
cc @litong01

2022-09-09 18:25 UTC, zirain commented
@yanrongshi 最近一个提交需要revert下处理下CLA

2022-09-12 01:36 UTC, zirain commented
@yanrongshi 你需要revert下commit，其中有个commit有我另外一个未签署cla的邮箱

命令大概如下：
```console
git reset HEAD~5
git add .
git commit -m "update content/zh/boilerplates/trace-generation.md"
git push -f
```

2022-09-19 01:40 UTC, windsonsea commented
Hope you can check more. 
FYI: Giving  a newline char is much friendly to review.

![Uploading image.png…]()

2022-09-25 08:50 UTC, windsonsea commented
Because of no response for a long time and such a small PR with less value, this PR is closed.

2022-09-25 08:50 UTC, closed without merging