updated for ist0153 - zhcn
istio/istio.io pull request #11727
Opened 2022-08-22 03:35 UTC by huan555

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-08-22 03:35 UTC, istio-testing commented
Hi @huan555. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-08-22 13:49 UTC, ericvn commented
/ok-to-test

2022-08-25 09:29 UTC, windsonsea commented
/easycla

2022-08-25 13:24 UTC, litong01 requested changes

2022-08-25 13:24 UTC, litong01 commented on content/zh/docs/reference/config/analysis/ist0153/index.md
> +这将导致忽略 `ADD` 操作。目前，只有 `MERGE` 操作可用于 `ROUTE_CONFIGURATION`。
looks like this is a bit inconsistent with the translation for 0154. can you make this similar to 0154?

这将导致`ADD` 操作被忽略

2022-08-25 13:24 UTC, litong01 commented
also missing CLA. please add your signature.

2022-09-08 23:22 UTC, windsonsea commented on content/zh/docs/reference/config/analysis/ist0153/index.md
> +以下示例中，如果一个 `EnvoyFilter` 附带有 `ADD` 补丁操作 ，该 `EnvoyFilter` 将被忽略：
```suggestion
以下示例中，如果一个 `EnvoyFilter` 附带有 `ADD` 补丁操作，该 `EnvoyFilter` 将被忽略：
```

2022-09-09 22:48 UTC, windsonsea commented
@huan555 Could you move this forward? 19 days passed.

2022-09-19 01:29 UTC, windsonsea commented
Hi @huan555 , could you take a look over the comment? If no any response for certain days, this PR will be closed. Thanks.

2022-09-19 02:59 UTC, huan555 commented
@windsonsea sorry for late, the change have been commited.

2022-09-19 03:03 UTC, windsonsea approved these changes

2022-10-09 03:34 UTC, zirain approved these changes

2022-10-09 04:20 UTC, merged

2022-10-09 04:26 UTC, zirain commented
/cherry-pick release-1.15

2022-10-09 04:27 UTC, istio-testing commented
@zirain: new pull request created: #12070

<details>

In response to [this](https://github.com/istio/istio.io/pull/11727#issuecomment-1272452137):

>/cherry-pick release-1.15


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>