zh: localize /reference/config/analysis/ist0155/
istio/istio.io pull request #11729
Opened 2022-08-22 11:36 UTC by jzhupup

Added the zh text to this topic:

`content/zh/docs/reference/config/analysis/ist0155/index.md`

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-08-22 11:36 UTC, istio-testing commented
Hi @jzhupup. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-08-22 13:48 UTC, ericvn commented
/ok-to-test

2022-08-22 14:12 UTC, istio-testing commented
@jzhupup: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_demo_istio.io | 61a01a1f019c1fbb3d05882cd8a93fc9d1f145dc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11729/doc.test.profile_demo_istio.io/1561711920489172992) | true | `/test doc.test.profile_demo`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-08-22 14:59 UTC, istio-testing commented
@jzhupup: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_demo_istio.io | 61a01a1f019c1fbb3d05882cd8a93fc9d1f145dc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11729/doc.test.profile_demo_istio.io/1561711920489172992) | true | `/test doc.test.profile_demo`
doc.test.profile_default_istio.io | 61a01a1f019c1fbb3d05882cd8a93fc9d1f145dc | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11729/doc.test.profile_default_istio.io/1561711920451424256) | true | `/test doc.test.profile_default`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-08-23 02:36 UTC, jzhupup commented
/retest-required

2022-08-24 12:57 UTC, litong01 requested changes

2022-08-24 12:57 UTC, litong01 commented on content/zh/docs/reference/config/analysis/ist0155/index.md
> +当 `EnvoyFilter` 没有设置优先级并使用相对的补丁操作（`INSERT_BEFORE/AFTER`、`REPLACE`、`MERGE`、`DELETE`）和 `proxyVersion` 时会出现此消息，这可能会导致 `EnvoyFilter` 升级期时没有被应用。使用 `INSERT_FIRST` 或 `ADD` 选项或设置优先级可能有助于确保 `EnvoyFilter` 被正确应
I think that here the term `relative patch` probably should be translated into `相关补丁` not `相对的补丁`, the following maybe a bit better.

没有设置优先级并且没有使用相关补丁操作

The last statement, could be a bit better like this.

在升级后，`proxyVersion` 可能会发生变化，升级后的使用它顺序可能不同与升级前的顺序。

2022-08-24 12:57 UTC, litong01 commented on content/zh/docs/reference/config/analysis/ist0155/index.md
> +因为 `REPLACE` 的相对操作是与 `proxyVersion` 一起使用，所以添加 `priority` 可以解决这个问题：
相关操作

2022-08-25 01:52 UTC, jzhupup commented on content/zh/docs/reference/config/analysis/ist0155/index.md
> +当 `EnvoyFilter` 没有设置优先级并使用相对的补丁操作（`INSERT_BEFORE/AFTER`、`REPLACE`、`MERGE`、`DELETE`）和 `proxyVersion` 时会出现此消息，这可能会导致 `EnvoyFilter` 升级期时没有被应用。使用 `INSERT_FIRST` 或 `ADD` 选项或设置优先级可能有助于确保 `EnvoyFilter` 被正确应
Thanks！

2022-08-25 02:10 UTC, zirain commented on content/zh/docs/reference/config/analysis/ist0155/index.md
> +当 `EnvoyFilter` 没有设置优先级并使用相对的补丁操作（`INSERT_BEFORE/AFTER`、`REPLACE`、`MERGE`、`DELETE`）和 `proxyVersion` 时会出现此消息，这可能会导致 `EnvoyFilter` 升级期时没有被应用。使用 `INSERT_FIRST` 或 `ADD` 选项或设置优先级可能有助于确保 `EnvoyFilter` 被正确应
不同于

2022-08-25 02:11 UTC, zirain commented on content/zh/docs/reference/config/analysis/ist0155/index.md
> +当 `EnvoyFilter` 没有设置优先级并没有使用相关补丁操作（`INSERT_BEFORE/AFTER`、`REPLACE`、`MERGE`、`DELETE`）和 `proxyVersion` 时会出现此消息，这可能会导致 `EnvoyFilter` 升级期时没有被应用。使用 `INSERT_FIRST` 或 `ADD` 选项或设置优先级可能有助于确保 `EnvoyFilter` 被正确
```suggestion
当 `EnvoyFilter` 没有设置优先级并没有使用相关补丁操作（`INSERT_BEFORE/AFTER`、`REPLACE`、`MERGE`、`DELETE`）和 `proxyVersion` 时会出现此消息，这可能会导致 `EnvoyFilter` 升级期时没有被应用。使用 `INSERT_FIRST` 或 `ADD` 选项或设置优先级可能有助于确保 `EnvoyFilter` 被正确应用。关注 `proxyVersion` 的原因是，在升级后，`proxyVersion` 可能会发生变化，升级后它的使用顺序可能不同于升级前的顺序。
```

2022-08-25 02:13 UTC, zirain commented on content/zh/docs/reference/config/analysis/ist0155/index.md
> +当 `EnvoyFilter` 没有设置优先级并没有使用相关补丁操作（`INSERT_BEFORE/AFTER`、`REPLACE`、`MERGE`、`DELETE`）和 `proxyVersion` 时会出现此消息，这可能会导致 `EnvoyFilter` 升级期时没有被应用。使用 `INSERT_FIRST` 或 `ADD` 选项或设置优先级可能有助于确保 `EnvoyFilter` 被正确
`升级后它的使用顺序可能不同于升级前`  这样读起来好像更顺畅

2022-08-25 02:20 UTC, litong01 commented on content/zh/docs/reference/config/analysis/ist0155/index.md
> +当 `EnvoyFilter` 没有设置优先级并没有使用相关补丁操作（`INSERT_BEFORE/AFTER`、`REPLACE`、`MERGE`、`DELETE`）和 `proxyVersion` 时会出现此消息，这可能会导致 `EnvoyFilter` 升级期时没有被应用。使用 `INSERT_FIRST` 或 `ADD` 选项或设置优先级可能有助于确保 `EnvoyFilter` 被正确
agreed.

2022-08-25 12:27 UTC, litong01 requested changes

2022-08-25 12:27 UTC, litong01 commented on content/zh/docs/reference/config/analysis/ist0155/index.md
> +当 `EnvoyFilter` 没有设置优先级并没有使用相关补丁操作（`INSERT_BEFORE/AFTER`、`REPLACE`、`MERGE`、`DELETE`）和 `proxyVersion` 时会出现此消息，这可能会导致 `EnvoyFilter` 升级期时没有被应用。使用 `INSERT_FIRST` 或 `ADD` 选项或设置优先级可能有助于确保 `EnvoyFilter` 被正确
can you also please change 升级期时 to 升级时? I am not really sure we ever say things like 升级期时. Just noticed that. Everything else looks good to me. Thanks.

2022-08-25 12:43 UTC, zirain commented on content/zh/docs/reference/config/analysis/ist0155/index.md
> +当 `EnvoyFilter` 没有设置优先级并没有使用相关补丁操作（`INSERT_BEFORE/AFTER`、`REPLACE`、`MERGE`、`DELETE`）和 `proxyVersion` 时会出现此消息，这可能会导致 `EnvoyFilter` 升级期时没有被应用。使用 `INSERT_FIRST` 或 `ADD` 选项或设置优先级可能有助于确保 `EnvoyFilter` 被正确
应该使用 `升级期间` ？ cc @litong01

2022-08-25 13:08 UTC, litong01 commented on content/zh/docs/reference/config/analysis/ist0155/index.md
> +当 `EnvoyFilter` 没有设置优先级并没有使用相关补丁操作（`INSERT_BEFORE/AFTER`、`REPLACE`、`MERGE`、`DELETE`）和 `proxyVersion` 时会出现此消息，这可能会导致 `EnvoyFilter` 升级期时没有被应用。使用 `INSERT_FIRST` 或 `ADD` 选项或设置优先级可能有助于确保 `EnvoyFilter` 被正确
@zirain I feel either 升级期间 or 升级时 should work. Thanks.

2022-08-26 01:01 UTC, jzhupup commented on content/zh/docs/reference/config/analysis/ist0155/index.md
> +当 `EnvoyFilter` 没有设置优先级并没有使用相关补丁操作（`INSERT_BEFORE/AFTER`、`REPLACE`、`MERGE`、`DELETE`）和 `proxyVersion` 时会出现此消息，这可能会导致 `EnvoyFilter` 升级期时没有被应用。使用 `INSERT_FIRST` 或 `ADD` 选项或设置优先级可能有助于确保 `EnvoyFilter` 被正确
ok

2022-08-26 01:10 UTC, zirain approved these changes
lgtm

2022-08-26 03:20 UTC, litong01 approved these changes
Thanks very much!

2022-08-26 03:21 UTC, merged