zh: localize /releases/1.14.x/announcing-1.14.3/
istio/istio.io pull request #11730
Opened 2022-08-22 13:07 UTC by windsonsea

Added zh text to: 
```
content/zh/news/releases/1.14.x/announcing-1.14.3/
```

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-08-22 13:14 UTC, istio-testing commented
@windsonsea: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 2fa52ae6e7c1483487e7ac0d3f77d97b8d7b3d4b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11730/lint_istio.io/1561701683392679936) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-08-25 13:05 UTC, litong01 requested changes

2022-08-25 13:05 UTC, litong01 commented on content/zh/news/releases/1.14.x/announcing-1.14.3/index.md
> +此版本修复了 [CVE-2022-31045](/zh/news/security/istio-security-2022-005/#cve-2022-31045)，
please change to the following:
此版本包括对[CVE-2022-31045]和其它有助于改善稳定性的修复。

2022-08-25 13:05 UTC, litong01 commented on content/zh/news/releases/1.14.x/announcing-1.14.3/index.md
> +- **修复** 修复了 `Sidecar` 中造成 `outboundTrafficPolicy` 变更不能始终生效的问题。([Issue #39794](https://github.com/istio/istio/issues/39794))
修复了一个在改变`outboundTrafficPolicy`后有时设置改变不能生效的问题。

2022-08-25 13:05 UTC, litong01 commented on content/zh/news/releases/1.14.x/announcing-1.14.3/index.md
> +- **移除** 从 `istio-ingress/egress` helm 值模板中移除了 `archs` 并有条件填充 `nodeAffinity`。
maybe change it to something like this?

**移除** 从 `istio-ingress/egress` helm 值模板中移除了 `archs`和有条件填充 `nodeAffinity`。的设置

2022-08-25 21:55 UTC, windsonsea commented on content/zh/news/releases/1.14.x/announcing-1.14.3/index.md
> +此版本修复了 [CVE-2022-31045](/zh/news/security/istio-security-2022-005/#cve-2022-31045)，
It will be easy to click this button when you add any comments:
![image](https://user-images.githubusercontent.com/79828097/186776017-291b5f89-ba20-4042-bc25-64c84fb71ecc.png)

2022-09-08 01:33 UTC, kebe7jun commented
@litong01 need your approve.

2022-10-09 03:35 UTC, zirain approved these changes

2022-10-09 05:09 UTC, merged

2022-10-09 05:10 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #12071