make helm install consistent with istioctl
istio/istio.io pull request #11762
Opened 2022-08-27 02:56 UTC by zirain

make helm install consistent with istioctl

fixes: https://github.com/istio/istio/issues/39049

cc @frankbu

2022-08-27 03:06 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 64d0af011007dd27e504d3b56e7175c9de38c13f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11762/lint_istio.io/1563359799356166144) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-08-27 03:45 UTC, istio-testing commented
@zirain: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 64d0af011007dd27e504d3b56e7175c9de38c13f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11762/lint_istio.io/1563359799356166144) | true | `/test lint`
doc.test.profile_none_istio.io | 64d0af011007dd27e504d3b56e7175c9de38c13f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11762/doc.test.profile_none_istio.io/1563359799544909824) | true | `/test doc.test.profile_none`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-08-27 07:57 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | 57c41d8dcaa06b8c0cfb67fa4784db229ad78348 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11762/doc.test.profile_none_istio.io/1563421798198939648) | true | `/test doc.test.profile_none`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-08-27 11:09 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | 66f01bf38a24b2c5ab92de75eb4ebb6d052d4fb4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11762/doc.test.profile_none_istio.io/1563470796121182208) | true | `/test doc.test.profile_none`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-08-28 03:26 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | afd921602c6dd1f469d39330566974aeb64286db | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11762/doc.test.profile_none_istio.io/1563716891447398400) | true | `/test doc.test.profile_none`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-08-28 06:41 UTC, istio-testing commented
@zirain: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | afd921602c6dd1f469d39330566974aeb64286db | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11762/doc.test.profile_none_istio.io/1563716891447398400) | true | `/test doc.test.profile_none`
gencheck_istio.io | ebf2414cad8fddeb3648919dbf44831a30355f1c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11762/gencheck_istio.io/1563777504123031552) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-08-28 07:35 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | 08cfe1c1535175480fea926c5b3d0767c615f8cd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11762/doc.test.profile_none_istio.io/1563779348459163648) | true | `/test doc.test.profile_none`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-08-28 14:49 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | ce3b1a40df39b32bec0bf92040c0838100dab159 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11762/doc.test.profile_none_istio.io/1563888822859599872) | true | `/test doc.test.profile_none`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-08-28 17:56 UTC, ericvn commented
Any feedback from @istio/wg-environments-maintainers ?

2022-08-28 21:08 UTC, howardjohn requested changes
This is intended - the use of istio-system is an anti-pattern explicitly not recommended

2022-08-29 14:41 UTC, howardjohn commented
If they are confused we should improve documentation, etc. Not proliferate
bad practices

On Mon, Aug 29, 2022 at 5:29 AM zirain ***@***.***> wrote:

> I also got some feedback same as istio/istio#39049
> <https://github.com/istio/istio/issues/39049> mentioned, the helm doc is
> different from istioctl, which confused istio rookie.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/istio/istio.io/pull/11762#issuecomment-1230221400>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEYGXJLOD2ZJ4XC2UKWAV3V3SULRANCNFSM57YSAZ7A>
> .
> You are receiving this because you are on a team that was mentioned.Message
> ID: ***@***.***>
>

2022-09-06 14:47 UTC, closed without merging