[zh] sync /news/releases/1.15.x/announcing-1.15/_index.md
istio/istio.io pull request #11773
Opened 2022-08-31 16:24 UTC by yanrongshi

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-09-01 02:16 UTC, rootsongjc commented on content/zh/news/releases/1.15.x/announcing-1.15/_index.md
> +4 月，我们宣布 Istio 已被提议成为 CNCF 的孵化项目。我们的团队一直在努力准备我们的申请，TOC 目前处于公开征求意见阶段。如果您想参加，请看这个帖子！
「请看这个帖子」这里是不是应该有个链接？不过我发现英文版的原文里也没有链接，这里可能漏掉了？

2022-09-01 02:46 UTC, litong01 requested changes

2022-09-01 02:46 UTC, litong01 commented on content/zh/news/releases/1.15.x/announcing-1.15/_index.md
> +这是 2022 年的第三个 Istio 版本。我们要感谢整个 Istio 社区帮助发布 Istio 1.15.0。
probably change it to something like this?

这是 2022 年发布的第三个 Istio 版本.

2022-09-01 02:46 UTC, litong01 commented on content/zh/news/releases/1.15.x/announcing-1.15/_index.md
> +特别感谢来自 Google 的发布经理 Sam Naser 和 Aryan Gupta、来自 Intel 的 Ziyang Xiao 和来自 Solo.io 的 Daniel Hawton。
can we add the following?
我们特别感谢来自

2022-09-01 14:49 UTC, yanrongshi commented on content/zh/news/releases/1.15.x/announcing-1.15/_index.md
> +4 月，我们宣布 Istio 已被提议成为 CNCF 的孵化项目。我们的团队一直在努力准备我们的申请，TOC 目前处于公开征求意见阶段。如果您想参加，请看这个帖子！
原文中没有这个链接，我去官网上查了，也没有这个类型的帖子

2022-09-02 02:12 UTC, rootsongjc commented on content/zh/news/releases/1.15.x/announcing-1.15/_index.md
> +4 月，我们宣布 Istio 已被提议成为 CNCF 的孵化项目。我们的团队一直在努力准备我们的申请，TOC 目前处于公开征求意见阶段。如果您想参加，请看这个帖子！
如果没有的话不如先把这句话删掉好了，省的让大家困惑。

2022-09-02 14:15 UTC, litong01 approved these changes
Thanks for your contributions.

2022-09-02 15:05 UTC, istio-testing commented
@yanrongshi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_default_istio.io | a2a8a8d5a1d612b6dc7499b0ebeb0d3f091e5a0e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11773/doc.test.profile_default_istio.io/1565705261522358272) | unknown | `/test doc.test.profile_default`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-02 15:21 UTC, Xunzhuo approved these changes

2022-09-02 15:21 UTC, Xunzhuo commented
/retest

2022-09-02 16:06 UTC, merged

2022-09-02 16:24 UTC, ericvn commented
/cherry-pick release-1.15

2022-09-02 16:25 UTC, istio-testing commented
@ericvn: new pull request created: #11794

<details>

In response to [this](https://github.com/istio/istio.io/pull/11773#issuecomment-1235692246):

>/cherry-pick release-1.15


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-09-02 16:58 UTC, istio-testing commented
@ericvn: new pull request could not be created: failed to create pull request against istio/istio.io#release-1.15 from head istio-testing:cherry-pick-11773-to-release-1.15: status code 422 not one of [201], body: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"A pull request already exists for istio-testing:cherry-pick-11773-to-release-1.15."}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}

<details>

In response to [this](https://github.com/istio/istio.io/pull/11773#issuecomment-1235692246):

>/cherry-pick release-1.15


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>