[zh]Sync content/zh/docs/tasks/security/authentication/mtls-migration/index.md
istio/istio.io pull request #11884
Opened 2022-09-10 07:16 UTC by yanrongshi

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-09-10 07:25 UTC, istio-testing commented
@yanrongshi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 9bd29aa8f23278a2b36d86d8cd6c5c3dbbce6de9 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11884/lint_istio.io/1568498551908995072) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-10 07:51 UTC, istio-testing commented
@yanrongshi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 3a5e52b461643743d403601cc891f427711d14c8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11884/lint_istio.io/1568505399823306752) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-10 08:14 UTC, windsonsea commented
Please resolve the lint error before reviewing.

2022-09-10 09:00 UTC, istio-testing commented
@yanrongshi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_default_istio.io | 8964a05567e5d2a09ad4d8e57a1fe0232ff48d1a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11884/doc.test.profile_default_istio.io/1568515285231603712) | true | `/test doc.test.profile_default`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-12 11:06 UTC, windsonsea commented
/retest

2022-09-12 11:20 UTC, windsonsea requested changes

2022-09-12 11:20 UTC, windsonsea commented on content/zh/docs/tasks/security/authentication/mtls-migration/index.md
> +* 创建两个命名空间，`foo` 和 `bar`，并它们上部署 [httpbin]({{< github_tree >}}/samples/httpbin)、[sleep]({{< github_tree >}}/samples/sleep) 和 sidecar。
```suggestion
* 创建两个命名空间：`foo` 和 `bar`，并在这两个命名空间上部署 [httpbin]({{< github_tree >}}/samples/httpbin)、[sleep]({{< github_tree >}}/samples/sleep) 和 Sidecar。
```

2022-09-12 11:20 UTC, windsonsea commented on content/zh/docs/tasks/security/authentication/mtls-migration/index.md
> +* 创建另一个命名空间 `legacy`，并在没有 sidecar 的情况下部署 [sleep]({{< github_tree >}}/samples/sleep)：
```suggestion
* 创建另一个命名空间 `legacy`，并在没有 Sidecar 的情况下部署 [sleep]({{< github_tree >}}/samples/sleep)：
```

2022-09-12 11:20 UTC, windsonsea commented on content/zh/docs/tasks/security/authentication/mtls-migration/index.md
> +* （使用 Curl 命令）从每个 sleep pod （命名空间为 `foo`，`bar` 或 `legacy`）分别向 `httpbin.foo` 发送 http 请求。所有请求都应成功响应，返回 HTTP code 200。
```suggestion
* （使用 curl 命令）从每个 Sleep Pod （命名空间为 `foo`、`bar` 或 `legacy`）分别向 `httpbin.foo` 发送 http 请求。所有请求都应成功响应，返回 HTTP code 200。
```

2022-09-12 11:20 UTC, windsonsea commented on content/zh/docs/tasks/security/authentication/mtls-migration/index.md
> +如果任何 Curl 命令失败，请确保可能干扰 httpbin 服务请求的现有身份验证策略或目标规则。
```suggestion
如果任何 curl 命令失败，请确保可能干扰 httpbin 服务请求的现有身份验证策略或目标规则。
```

2022-09-12 11:20 UTC, windsonsea commented on content/zh/docs/tasks/security/authentication/mtls-migration/index.md
> +{{< /text >}}
```suggestion
    {{< text bash >}}
    $ kubectl delete peerauthentication -n istio-system default
    {{< /text >}}
```

2022-09-12 11:20 UTC, windsonsea commented on content/zh/docs/tasks/security/authentication/mtls-migration/index.md
>  $ kubectl delete ns foo bar legacy
The four rows need 4 spaces indentation.

2022-09-17 12:07 UTC, yanrongshi commented on content/zh/docs/tasks/security/authentication/mtls-migration/index.md
> +如果任何 Curl 命令失败，请确保可能干扰 httpbin 服务请求的现有身份验证策略或目标规则。
或许应该统一成大写？

2022-09-17 12:12 UTC, windsonsea commented on content/zh/docs/tasks/security/authentication/mtls-migration/index.md
> +如果任何 Curl 命令失败，请确保可能干扰 httpbin 服务请求的现有身份验证策略或目标规则。
搜索了一下 k8s 和 istio repo，都是纯小写 `curl`

2022-09-17 12:18 UTC, windsonsea approved these changes
Looks good to me, thanks.

2022-09-17 12:58 UTC, merged

2022-09-17 12:59 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #11933