1.13.7
istio/istio.io pull request #11905
Opened 2022-09-14 04:46 UTC by jzhupup

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-09-14 04:46 UTC, istio-testing commented
Hi @jzhupup. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-09-14 06:07 UTC, zirain requested changes
should not contains 1.13.8

2022-09-14 11:43 UTC, windsonsea requested changes
Respect comes from your carefulness.

2022-09-14 11:43 UTC, windsonsea commented on content/zh/news/releases/1.13.x/announcing-1.13.7/index.md
> +此版本包含针对 [CVE-2022-31045](/zh/news/security/istio-security-2022-005/#cve-2022-31045) 和错误修复以提高稳定性。我们建议用户安装此版本而不是 Istio 1.13.6，因为 Istio 1.13.7 包含上述 CVE 修复。
```suggestion
此版本包含针对 [CVE-2022-31045](/zh/news/security/istio-security-2022-005/#cve-2022-31045) 所做的修复和其他漏洞修复，以提高稳健性。我们建议用户安装此版本来替代未包含上述 CVE 修复的 Istio 1.13.6。
```

2022-09-14 11:43 UTC, windsonsea commented on content/zh/news/releases/1.13.x/announcing-1.13.7/index.md
> +这个版本说明描述了 Istio 1.13.6 和 Istio 1.13.7 之间的区别。
```suggestion
这个发布说明描述了 Istio 1.13.6 和 Istio 1.13.7 之间的区别。
```

2022-09-14 11:43 UTC, windsonsea commented on content/zh/news/releases/1.13.x/announcing-1.13.7/index.md
> +其中包括 9 个安全修复程序。如果你在本地使用 Go，我们建议你升级到这个较新的 Go 版本。
A clause is missing:
FYI, [Go 1.18.4 has been released](https://groups.google.com/g/golang-announce/c/nqrv9fbR0zE),
which includes 9 security fixes. We recommend you to upgrade to this newer Go version if you are using Go locally.

2022-09-14 15:39 UTC, ericvn commented
/ok-to-test

2022-09-14 15:49 UTC, istio-testing commented
@jzhupup: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | b396b45a96aa541bd15c0f0035dded4c37e7e03b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11905/lint_istio.io/1570074681417928704) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-15 04:46 UTC, windsonsea commented on content/zh/news/releases/1.13.x/announcing-1.13.7/index.md
> +其中包括 9 个安全修复。如果你在本地使用 Go，我们建议你升级到这个较新的 Go 版本。
```suggestion
其中包括 9 个安全修复。如果您在本地使用 Go，我们建议您升级到这个较新的 Go 版本。
```

2022-09-15 04:47 UTC, windsonsea commented on content/zh/news/releases/1.13.x/announcing-1.13.7/index.md
> +其中包括 9 个安全修复。如果你在本地使用 Go，我们建议你升级到这个较新的 Go 版本。
您 is preferred in Istio localization.

2022-09-17 14:14 UTC, windsonsea approved these changes

2022-09-17 14:20 UTC, zirain approved these changes

2022-09-17 14:51 UTC, merged