[zh]Sync Release notes for Istio 1.13.8
istio/istio.io pull request #11902
Opened 2022-09-13 11:52 UTC by jzhupup

follow up of  https://github.com/istio/istio.io/pull/11898

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-09-13 11:52 UTC, istio-testing commented
Hi @jzhupup. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-09-13 11:56 UTC, zirain commented
/ok-to-test

2022-09-13 12:02 UTC, windsonsea requested changes
You copied with a wrong folder name. The correct name shall be `1.13.8` instead of current `1.3.8`.

2022-09-14 01:04 UTC, jzhupup commented
> content/zh/news/releases/1.3.x/announcing-1.3.8/index.md
thx.

2022-09-14 01:12 UTC, closed without merging