zh:sync /setup/upgrade/helm/
istio/istio.io pull request #11929
Opened 2022-09-17 09:26 UTC by windsonsea

Added zh text to:
```
content/zh/docs/setup/upgrade/helm/index.md
```

- [x] Docs

2022-09-17 09:28 UTC, istio-testing commented
@windsonsea: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 5c9b31334115420b72b45546838bd4a30a85cb21 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11929/lint_istio.io/1571068031814078464) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-27 03:10 UTC, zirain commented on content/zh/docs/setup/upgrade/helm/index.md
> +1. 升级 Istio 基础 Chart，将新的修订版作为默认值。
这里的base不建议翻译就比如 gateway istiod 本质是helm chart的名称，无需要翻译

2022-09-27 03:10 UTC, zirain commented on content/zh/docs/setup/upgrade/helm/index.md
> +### 稳定修订标签（实验）{#stable-revision-labels}
```suggestion
### 稳定修订标签（实验特性/预览特性）{#stable-revision-labels}
```

2022-09-27 03:20 UTC, zirain commented on content/zh/docs/setup/upgrade/helm/index.md
> +这些命令将在您的集群中创建新的 `MutatingWebhookConfiguration` 资源，但是由于 `kubectl` 手动应用这些模板，所以这些资源不属于任何 Helm Chart。参见以下指示说明来卸载修订标记。
```suggestion
这些命令将在您的集群中创建新的 `MutatingWebhookConfiguration` 资源，由于是通过 `kubectl` 手动应用这些模板，所以这些资源不属于任何 Helm Chart。参见以下指示说明来卸载修订标记。
```

2022-09-27 03:23 UTC, zirain commented on content/zh/docs/setup/upgrade/helm/index.md
> +### 热升级{#in-place-upgrade}
确实下是不是其他地方翻译成 `原地升级`，这里感觉使用 `原地升级` 更准确一些。

2022-09-27 03:25 UTC, zirain requested changes

2022-09-27 03:25 UTC, zirain commented on content/zh/docs/setup/upgrade/helm/index.md
> +1. 升级 Istio 基础 Chart：
同上，无需翻译

2022-09-27 03:25 UTC, zirain commented on content/zh/docs/setup/upgrade/helm/index.md
> +1. 升级 Istio 发现 Chart：
同上，无需翻译

2022-09-27 03:25 UTC, zirain commented on content/zh/docs/setup/upgrade/helm/index.md
> +1. （可选）升级集群中安装的网关 Chart：
同上，无需翻译

2022-09-27 06:56 UTC, zirain commented on content/zh/docs/setup/upgrade/helm/index.md
> +### 稳定修订标签（实验特性/预览特性）{#stable-revision-labels}
实验特性 或 预览特性 二选一就可以

2022-09-27 07:36 UTC, windsonsea commented on content/zh/docs/setup/upgrade/helm/index.md
> +### 稳定修订标签（实验特性/预览特性）{#stable-revision-labels}
lol, got it.

2022-09-27 08:11 UTC, zirain approved these changes

2022-09-27 08:21 UTC, merged

2022-09-27 08:22 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #12012