zh:sync /tasks/security/cert-management/custom-ca-k8s/
istio/istio.io pull request #11923
Opened 2022-09-17 03:43 UTC by windsonsea

Sync with the en upstream:

```
content/zh/docs/tasks/security/cert-management/custom-ca-k8s/index.md
```
- [x] Docs

2022-09-17 03:55 UTC, istio-testing commented
@windsonsea: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 8db6eef80d2f181c2d7fd69fa2f6a9dd15043e89 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11923/lint_istio.io/1570981816913891328) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-17 04:38 UTC, istio-testing commented
@windsonsea: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | d0dc4947c258cbd424f196ddfdf238da664c2e38 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11923/lint_istio.io/1570992918016036864) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-17 06:36 UTC, zirain requested changes

2022-09-17 06:36 UTC, zirain commented on content/zh/docs/tasks/security/cert-management/custom-ca-k8s/index.md
> +可以预期的是，如果工作负载的证书是同一个证书签名者颁发的，则这些工作负载可以与 MTLS 通信，而不同签名者签名的工作负载则不能这样。
此句后面漏了一句移除了，是有特殊考虑吗？

2022-09-17 07:16 UTC, windsonsea commented on content/zh/docs/tasks/security/cert-management/custom-ca-k8s/index.md
> +可以预期的是，如果工作负载的证书是同一个证书签名者颁发的，则这些工作负载可以与 MTLS 通信，而不同签名者签名的工作负载则不能这样。
😺 不小心给删掉了，感谢发现 🙏

2022-09-18 14:30 UTC, zirain approved these changes

2022-09-18 16:30 UTC, merged

2022-09-18 16:31 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #11952