[zh]Sync /docs/tasks/traffic-management/ingress/ingress-control/index.md
istio/istio.io pull request #11932
Opened 2022-09-17 12:27 UTC by yanrongshi

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-09-17 12:34 UTC, windsonsea commented on content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
> +如果您正在 Linux 系统上使用 Kind 集群运行 Istio，请、遵循[设置  MetalLB 指南]来获得类型为 `LoadBalancer` 的服务。
这是个啥，提交以后，自己一定要 review 读一遍！

2022-09-17 12:42 UTC, yanrongshi commented on content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
> +如果您正在 Linux 系统上使用 Kind 集群运行 Istio，请、遵循[设置  MetalLB 指南]来获得类型为 `LoadBalancer` 的服务。
好的

2022-09-17 14:18 UTC, windsonsea commented on content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
> +如果您正在 Linux 系统上使用 Kind 集群运行 Istio，请遵循[设置 MetalLB 指南]来获得类型为 `LoadBalancer` 的服务。
Hey, could I ask where is the url of link? Do you know what is review?

2022-09-17 14:29 UTC, windsonsea requested changes
请认真对待每一件事。
Don't show your careless everywhere. That's a bad and polluted impression.

2022-09-17 14:29 UTC, windsonsea commented on content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md
> +如果您正在 Linux 系统上使用 Kind 集群运行 Istio，请遵循[设置 MetalLB 指南]来获得类型为 `LoadBalancer` 的服务。
这么小的修改，在反复要求检查之后，还是出现这么低级的错误，很难理解你这 1 年多的 Istio 经验体现在哪里？？？

2022-09-17 16:04 UTC, windsonsea requested changes
1. Line 56 and 80 may also need to be localized.
   {{< tab name="external load balancer" category-value="external-lb" >}}
   {{< tab name="node port" category-value="node-port" >}}
2. If you can open and read [this page](https://istio.io/latest/zh/docs/tasks/traffic-management/ingress/ingress-control/), it's easy to find more:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/79828097/190865887-a2684e17-ef0a-4587-9f92-dfb9b2d6845a.png">

> Note: It's very easy to find if you are careful or careless in any PR you opened, which will show your personality to everyone.

2022-09-19 17:18 UTC, istio-testing commented
@yanrongshi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | 2078c2c665856ccb9a820661abfaf53461b64976 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11932/doc.test.profile_none_istio.io/1571900628572049408) | true | `/test doc.test.profile_none`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-19 17:20 UTC, istio-testing commented
@yanrongshi: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
doc.test.profile_none_istio.io | 2078c2c665856ccb9a820661abfaf53461b64976 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11932/doc.test.profile_none_istio.io/1571900628572049408) | true | `/test doc.test.profile_none`
doc.test.profile_default_istio.io | 2078c2c665856ccb9a820661abfaf53461b64976 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/11932/doc.test.profile_default_istio.io/1571900628488163328) | true | `/test doc.test.profile_default`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-19 17:36 UTC, yanrongshi commented
/retest

2022-09-19 17:36 UTC, yanrongshi commented
Wait for the upstream to repair

2022-09-19 17:36 UTC, yanrongshi commented
/hold

2022-09-20 01:36 UTC, zirain requested changes
same as https://github.com/istio/istio.io/pull/11974？

2022-09-30 12:54 UTC, closed without merging