[zh] Update docs/concepts/wasm
istio/istio.io pull request #11936
Opened 2022-09-17 14:58 UTC by my-git9

[zh] Update /zh/docs/concepts/wasm
The en docs now is:
<img width="978" alt="image" src="https://user-images.githubusercontent.com/76980726/190863292-ccf851da-2c4b-4ef5-af2e-edd2706f752c.png">

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-09-17 16:23 UTC, zirain requested changes

2022-09-17 16:23 UTC, zirain commented on content/zh/docs/concepts/wasm/index.md
> +您可以按照本指南使用 C++ 实现 Wasm 扩展。
missing hyperlink？

2022-09-18 06:59 UTC, windsonsea approved these changes

2022-09-18 08:55 UTC, zirain approved these changes

2022-09-18 08:56 UTC, merged

2022-09-18 08:57 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #11944