zh:sync /ops/configuration/telemetry/envoy-stats/
istio/istio.io pull request #12017
Opened 2022-09-28 12:00 UTC by windsonsea

Sync with the en version
```
content/zh/docs/ops/configuration/telemetry/envoy-stats/index.md
```
- [x] Docs

2022-09-28 12:18 UTC, litong01 requested changes

2022-09-28 12:18 UTC, litong01 commented on content/zh/docs/ops/configuration/telemetry/envoy-stats/index.md
> +您也可以通过使用 `proxy.istio.io/config` 注解覆盖全局的数据统计匹配配置。例如，为了配置生成与上面相同的统计数据，您可以在一个 Gateway 代理或者一个工作负载上添加下面的注解：
I read the above many times, it is really hard for me to understand. I wonder if you are open to change the first sentenace to the following:

您也可以通过使用单个Proxy的 `proxy.istio.io/config` 注解配置来改变全局数据统计的相应配置。

2022-09-28 12:46 UTC, windsonsea commented on content/zh/docs/ops/configuration/telemetry/envoy-stats/index.md
> +您也可以通过使用 `proxy.istio.io/config` 注解覆盖全局的数据统计匹配配置。例如，为了配置生成与上面相同的统计数据，您可以在一个 Gateway 代理或者一个工作负载上添加下面的注解：
👍  The legacy text might come from MT. Seems it is relatively easy to read now.

2022-10-09 03:33 UTC, zirain approved these changes
lgtm

2022-10-09 04:20 UTC, merged

2022-10-09 04:22 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #12068