Translation
istio/istio.io pull request #12064
Opened 2022-10-08 08:34 UTC by liangyongzhenya

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-10-08 08:34 UTC, istio-testing commented
Hi @liangyongzhenya. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-10-08 08:39 UTC, kfaseela commented
/ok-to-test

2022-10-08 08:39 UTC, istio-testing commented
@liangyongzhenya: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | ebf9c24b58a7b181feed6703d0486c5f14ce0239 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12064/lint_istio.io/1578666274211237888) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-08 08:43 UTC, rootsongjc commented on content/zh/news/releases/1.15.x/announcing-1.15.2/index.md
> +标题。宣布Istio 1.15.2发布
这些 Hugo 文档的配置字段不需要翻译，否则文档将无法渲染。

2022-10-08 08:51 UTC, zirain requested changes
如果不熟悉工作流，请先参考别人的做法。例如：
https://github.com/istio/istio.io/pull/12061

最好能够提供一个友好的标题

2022-10-08 08:53 UTC, zirain commented
/wait https://github.com/istio/istio.io/pull/12055

2022-10-08 09:49 UTC, istio-testing commented
@liangyongzhenya: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 523081aa58dc54be73d2250cdd5fb18b5f762289 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12064/lint_istio.io/1578681144382066688) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-08 12:47 UTC, windsonsea reviewed
请先修改几个明显的问题：
- 中英之间空格
- 式样与 en 需一致

参阅 https://github.com/istio/istio.io/pull/12028/files

2022-10-09 03:17 UTC, istio-testing commented
@liangyongzhenya: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | c5577a930ce845da5089c029b5ebd16c44765385 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12064/lint_istio.io/1578944780321165312) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-09 03:24 UTC, windsonsea commented
Thanks, you may need to perform the following steps before review:
1. Sign the cla/google: https://github.com/istio/istio.io/pull/12064/checks?check_run_id=8784849567
2. Fix the lint errors: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12064/lint_istio.io/1578944780321165312

2022-10-11 08:31 UTC, istio-testing commented
@liangyongzhenya: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 0f61267300ddd335da0fa138fc65430661710dcf | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12064/lint_istio.io/1579748830302179328) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-11 12:57 UTC, ericvn commented
Setting DNM until 1.15.2 is released.

2022-10-11 12:58 UTC, ericvn commented
Also, the original PR is changing slightly. Some changes need to be reflected here like like 12 which is changes in 1.15.2 from 1.15.1.

2022-10-11 19:43 UTC, ericvn commented
1.15.2 RN is now merged in the release branch and soon to be merged in the main branch.

2022-10-12 10:38 UTC, istio-testing commented
@liangyongzhenya: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 1ca4f7b41a064d1ef6553624b5fd40c9881ad9a4 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12064/lint_istio.io/1580145408443682816) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-12 10:42 UTC, istio-testing commented
@liangyongzhenya: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 769ab2ca0ee479a5e1080b7ff150f14df6e59206 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12064/lint_istio.io/1580146545859235840) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-12 10:59 UTC, windsonsea requested changes
Please try to look details when you handle text job.

github 是职场的延伸，请认真对待每一个字、每一句话

2022-10-12 10:59 UTC, windsonsea commented on content/zh/news/releases/1.15.x/announcing-1.15.2/index.md
> +title: Istio 1.15.2
```suggestion
title: Istio 1.15.2 发布
```

2022-10-12 10:59 UTC, windsonsea commented on content/zh/news/releases/1.15.x/announcing-1.15.2/index.md
> +该版本包括 Go 1.19.2（2022-10-04发布）中对 `archive/tar`、`net/http/httputil` 和 `regexp` 包的安全修复。
```suggestion
该版本包括 Go 1.19.2（2022-10-04 发布）中对 `archive/tar`、`net/http/httputil` 和 `regexp` 包的安全修复。
```

2022-10-12 10:59 UTC, windsonsea commented on content/zh/news/releases/1.15.x/announcing-1.15.2/index.md
> +这个版本包含了改进鲁棒性的错误修正。
```suggestion
这个版本包含了改进稳健性的漏洞修复。
```

2022-10-12 10:59 UTC, windsonsea commented on content/zh/news/releases/1.15.x/announcing-1.15.2/index.md
> +本发布说明描述了 Istio 1.15.2 和 Istio 1.15.2 之间的不同之处。
```suggestion
本发布说明描述了 Istio 1.15.1 和 Istio 1.15.2 之间的不同之处。
```

2022-10-12 10:59 UTC, windsonsea commented on content/zh/news/releases/1.15.x/announcing-1.15.2/index.md
> +-  **修复** 修复了 在1.14.0中，直通集群的默认 "idleTimeout "被改为 "0s"，禁用了超时的问题。恢复了之前的行为，使用 Envoy 的默认值1小时。([问题#41114](https://github.com/istio/istio/issues/41114))
```suggestion
-  **修复** 修复了 在 1.14.0 中 Passthrough 集群的默认 `idleTimeout` 更改为 `0s` 会禁用超时的问题。将其恢复为之前的行为，即使用 Envoy 的默认值 1 小时。([Issue #41114](https://github.com/istio/istio/issues/41114))
```

2022-10-12 10:59 UTC, windsonsea commented on content/zh/news/releases/1.15.x/announcing-1.15.2/index.md
> +-  **修复** 修复了 网关 API 集成，使其在删除 `v1alpha2` 版本时不会失败。
```suggestion
-  **修复** 修复了移除 `v1alpha2` 版本时网关 API 集成不会失败的问题。
```

2022-10-12 10:59 UTC, windsonsea commented on content/zh/news/releases/1.15.x/announcing-1.15.2/index.md
> +-  **修复** 修复了 对已废弃的自动缩放设置的处理。([问题 #41011](https://github.com/istio/istio/issues/41011))
```suggestion
-  **修复** 修复了处理已弃用的自动缩放设置的问题。([Issue #41011](https://github.com/istio/istio/issues/41011))
```

2022-10-12 13:37 UTC, istio-testing commented
@liangyongzhenya: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | fad7f7ff5a221321d22600943f11d5238f056d6e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12064/lint_istio.io/1580190456514351104) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-12 23:50 UTC, windsonsea commented
Please carefully read those comments rather than only pick some to apply. One tip is you can copy/paste the suggested text.

The lint error for your info:
```
ERROR 2022/10/12 13:37:15 Page description doesn't end with a period: 'Istio 1.15.2 补丁发布'
```

2022-10-14 02:46 UTC, windsonsea commented
Please check those comments again and click `Resolve conversation` if you have corrected all, or you can give some feedbacks.

2022-10-14 03:04 UTC, istio-testing commented
@liangyongzhenya: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 6096e7349211aa6875488d4032388dc9d738867c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12064/lint_istio.io/1580755910614061056) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-14 03:10 UTC, istio-testing commented
@liangyongzhenya: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 829ca15e0fa9b00fe564f9c7637f82c2fc7bd163 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12064/lint_istio.io/1580757178728321024) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-14 03:20 UTC, istio-testing commented
@liangyongzhenya: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 3a929b0a30a666bd9484d20e2576cfa0ea2cd741 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12064/lint_istio.io/1580759949871419392) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-14 04:35 UTC, windsonsea commented on content/zh/news/releases/1.15.x/announcing-1.15.2/index.md
> +-  **修复** 修复了 对已废弃的自动缩放设置的处理。([问题 #41011](https://github.com/istio/istio/issues/41011))
确定看懂这条 comments 了？会复制粘贴吗？
Issue 不用翻译！

2022-10-14 07:14 UTC, windsonsea approved these changes
lgtm

2022-10-14 07:14 UTC, windsonsea commented
/retest

2022-10-15 15:59 UTC, closed without merging