[zh] sync/releases/1.8.x/announcing-1.8.3/index.md
istio/istio.io pull request #12103
Opened 2022-10-16 12:33 UTC by liangyongzhenya

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ x ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-10-16 12:33 UTC, istio-testing commented
Hi @liangyongzhenya. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-10-17 01:51 UTC, windsonsea reviewed
Please remember those comments a reviewer has provided to you before. Thanks for your contribution.

请谨记 reviewer 给的 comments，之所以会给你 negative 反馈，是因为你需要的进步的空间还很大。如果三番五次还是同样的粗心大意，招致批评是非常正常的。

2022-10-17 01:51 UTC, windsonsea commented on content/zh/news/releases/1.8.x/announcing-1.8.3/index.md
> +这个版本包含了错误修复，以提高稳定性。本发布说明了 Istio 1.8.2 和 Istio 1.8.3 之间的不同之处。
```suggestion
这个版本包含了错误修复，以提高稳定性。本发布说明描述了 Istio 1.8.2 和 Istio 1.8.3 之间的不同之处。
```

2022-10-17 01:51 UTC, windsonsea commented on content/zh/news/releases/1.8.x/announcing-1.8.3/index.md
> +## 安全
```suggestion
## 安全
```
Give an anchor please.

2022-10-17 01:51 UTC, windsonsea commented on content/zh/news/releases/1.8.x/announcing-1.8.3/index.md
> +Istio 1.8.3 将不会包含之前在 [discuss.istio.io](https://discuss.istio.io/t/upcoming-istio-1-7-8-and-1-8-3-security-release/9593) 上公布的安全修复程序。
```suggestion
Istio 1.8.3 将不会包含之前在 [discuss.istio.io](https://discuss.istio.io/t/upcoming-istio-1-7-8-and-1-8-3-security-release/9593) 上公布的安全修复。
```

2022-10-17 01:51 UTC, windsonsea commented on content/zh/news/releases/1.8.x/announcing-1.8.3/index.md
> +目前还没有计划的日期。请放心，这是 Istio 产品安全工作组的首要任务，但由于细节问题，我们无法发布更多信息，延迟的公告可以在 [这里](https://discuss.istio.io/t/istio-1-7-8-and-1-8-3-cve-fixes-delayed/9663) 查看。
```suggestion
目前还没有计划的日期。当然这是 Istio 产品安全工作组的首要任务，但由于细节问题，我们无法发布更多信息，有关此延迟的公告请参阅[这里](https://discuss.istio.io/t/istio-1-7-8-and-1-8-3-cve-fixes-delayed/9663)。
```

2022-10-17 01:51 UTC, windsonsea commented on content/zh/news/releases/1.8.x/announcing-1.8.3/index.md
> +## 变更
need to add an anchor.

2022-10-17 01:51 UTC, windsonsea commented on content/zh/news/releases/1.8.x/announcing-1.8.3/index.md
> +- **修复** Envoy 中 TLS 初始化期间聚合集群的问题。
```suggestion
- **修复** 修复了 Envoy 中 TLS 初始化期间聚合集群的问题。
```
参照本句修复以下的风格

2022-10-17 01:57 UTC, windsonsea requested changes
Please change the style by following comments and the newest release notes.

2022-10-17 01:57 UTC, windsonsea commented on content/zh/news/releases/1.8.x/announcing-1.8.3/index.md
> +- **修复** 使用 `Sidecar` `ingress` 配置时，Istio 1.8 导致 1.7 代理配置错误的问题。
```suggestion
- **修复** 修复了使用 `Sidecar` `ingress` 配置时会导致 Istio 1.8 不正确地配置 Istio 1.7 代理的问题。
```

2022-10-17 02:22 UTC, kebe7jun commented
1.8.x 的版本过时了，不需要再维护了哈。

2022-10-17 10:19 UTC, Arhell reviewed
/ok-to-test

2022-10-17 10:32 UTC, istio-testing commented
@liangyongzhenya: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 291b2b0f1316188587be3c81fdbb9b8eeeba9b7c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12103/lint_istio.io/1581953045258833920) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-17 13:10 UTC, windsonsea commented
This will be closed since the version is outdated. We need not to maintain it further.

2022-10-17 13:10 UTC, closed without merging