zh: docs/tasks/traffic-management/ingress/secure-ingress/
istio/istio.io pull request #12120
Opened 2022-10-19 11:53 UTC by rootsongjc

Mainly update the [Secure Gateways](docs/tasks/traffic-management/ingress/secure-ingress/) Chinese page.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2022-10-19 12:05 UTC, istio-testing commented
@rootsongjc: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 678ef684fe43f09fc61c8629de98703f7297625d | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12120/lint_istio.io/1582701450574696448) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-20 02:59 UTC, zirain requested changes
can you please checkout from master branch to reduce the number of commit for better review?

2022-10-20 02:59 UTC, zirain commented on content/zh/blog/2022/gateway-api-beta/index.md
> +SIG Network 作为供应商中立论坛，确保服务网格社区使用相同的语义来实现网关 API，我们期待有一个标准 API ，它适用于所有的项目，无论其技术堆栈或代理如何。
```suggestion
SIG Network 作为供应商中立论坛，确保服务网格社区使用相同的语义来实现网关 API，我们期待有一个标准 API ，它适用于所有的项目，无论其使用任何技术栈或代理软件。
```

2022-10-20 02:59 UTC, zirain commented on content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
> +* 参考[安装指南](/zh//docs/setup/)部署 Istio。
```suggestion
* 参考[安装指南](/zh/docs/setup/)部署 Istio。
```

2022-10-20 03:00 UTC, zirain commented on content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
>  ---
prefer to split this page to a single PR

2022-10-20 03:10 UTC, windsonsea reviewed
Thanks for and admire your good quality about trans.

参考以下步骤同时提很多 PR：

1. 第一个 PR
  ```
  git checkout master
  git checkout -b zh-secure-gateway1
  ```
2. 提交第一个 PR 后，创建第二个 PR
  ```
  git checkout master
  git checkout -b zh-secure-gateway2
  ```

2022-10-20 03:10 UTC, windsonsea commented on content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
> +### 秘钥格式 {#key-formats}
```suggestion
### 密钥格式 {#key-formats}
```
本页其他地方用的都是 `密钥`

2022-10-20 03:10 UTC, windsonsea commented on content/zh/boilerplates/gateway-api-support.md
> +Istio 打算在[未来](/zh/blog/2022/gateway-api-beta/)将 Kubernetes Gateway API 作为流量管理的默认 API。下面的说明允许您在网格中配置流量管理时选择使用 [Gateway API](https://gateway-api.sigs.k8s.io/) 或 Istio 配置 API。根据您的偏好，按照 `Gateway API` 或 `
```suggestion
Istio 打算在[未来](/zh/blog/2022/gateway-api-beta/)将 Kubernetes [Gateway API](https://gateway-api.sigs.k8s.io/) 作为流量管理的默认 API。下面的说明允许您在网格中配置流量管理时选择使用 Gateway API 或 Istio 配置 API。根据您的偏好，按照 `Gateway API` 或 `Istio classic` 标签下的说明进行操作。
```
通常在第一次出现时加链接，也与 en 一致。

2022-10-20 03:52 UTC, rootsongjc commented
> Thanks for and admire your good quality about trans.
> 
> 参考以下步骤同时提很多 PR：
> 
> 1. 第一个 PR
> 
> ```
> git checkout master
> git checkout -b zh-secure-gateway1
> ```
> 
> 2. 提交第一个 PR 后，创建第二个 PR
> 
> ```
> git checkout master
> git checkout -b zh-secure-gateway2
> ```

了解，只是我想一次多修改一些内容，来回提交 PR 太麻烦了，很多页面都有些小问题，我看到就一并都改了。

2022-10-20 04:29 UTC, rootsongjc commented on content/zh/docs/tasks/traffic-management/ingress/secure-ingress/index.md
>  ---
这个 PR CLA 有些问题，我关闭了重新提交吧。

2022-10-20 04:29 UTC, closed without merging

2022-10-20 04:44 UTC, rootsongjc commented
Please see the new PR: https://github.com/istio/istio.io/pull/12124