Fix issues about glossary reference
istio/istio.io pull request #12863
Opened 2023-03-09 10:54 UTC by windsonsea

When reviewing #12842, it is found if an incomplete `{{< gloss >}}control plane{{< /gloss >}}` is translated into `{{< gloss >}}控制面板{{< /gloss >}}`, ci raised an error:

```
unrecognized character in shortcode action: U+003E '>'. Note: Parameters with non-alphanumeric args must be quoted
```
So have a try to change it to `{{< gloss "control plane" >}}control plane{{< /gloss >}}`. Hope it works.

- [x] Docs

2023-03-09 14:36 UTC, frankbu commented
You should not need to change the en docs because you want to use a different display string in zh; you should do this in the zh docs only.

2023-03-09 14:38 UTC, frankbu requested changes
I'm not sure this will work, but regardless, it should only be done in zh docs.

2023-03-10 01:29 UTC, windsonsea commented
Those changes are mainly for fixing inconsistency, which may cause a trap for localization and also a part of bad doc, for example:

- line 27: {{< gloss >}}control plane{{< /gloss >}}
- line 54: {{< gloss "cluster" >}}clusters{{< /gloss >}}
- line 74: {{< gloss >}}cluster{{< /gloss >}}
- line 93: {{< gloss "cluster" >}}clusters{{< /gloss >}}
- line 124: {{< gloss "namespace sameness" >}}namespace sameness{{< /gloss >}}
- line 186: {{< gloss >}}workload instance{{< /gloss >}}s
- line 199: {{< gloss "workload instance" >}}workload instances{{< /gloss >}}
- and more

2023-03-10 14:54 UTC, frankbu commented
> Those changes are mainly for fixing inconsistency ...

There is no inconsistency. The consistent rule is:

1. If the display text is exactly the same as the glossary entry, then the reference is like this:
    `{{< gloss >}}gloss-entry{{< /gloss >}}`
2. If the display text is different from the glossary entry, then the reference is like this:
    `{{< gloss "gloss-entry" >}}some-different-text{{< /gloss >}}`

I'm guessing you will always want to use the second form in the zh docs, but there's no need to make the en ones unnecessarily more complicated by using the second form even when `gloss-entry == some-different-text`

2023-03-10 19:26 UTC, windsonsea commented
Well, then this PR can be closed though it may cause some problems to localization efforts.

2023-03-10 19:26 UTC, closed without merging