add tips for using `[]` as a separator
istio/istio.io pull request #13188
Opened 2023-05-12 17:03 UTC by wulianglongrd

Jwt claim based routing now support using `[]` as a seprator, see https://github.com/istio/istio/pull/44355

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2023-05-12 17:32 UTC, ericvn commented
One issue is https://github.com/istio/istio/pull/44355 is part of the main istio branch and not cherry-picked to the 1.18 branch. This repo main branch is specifically for 1.18 and will become istio.io when it's released. As such, this PR will need to wait to be merged after 1.18.0 is released and this branch becomes the istio.io 1.18 branch, or the change would need to be part of istio 1.18.

2023-05-12 17:33 UTC, ericvn requested changes
Prevent this from merging until the upstream change is in 1.18 or we have branched this repo after the 1.18.0 release.

2023-05-12 17:40 UTC, wulianglongrd commented
got it, thanks.

2023-06-08 01:08 UTC, wulianglongrd commented
remove do-not-merge since 1.18 has been released

2023-06-08 15:04 UTC, ericvn approved these changes

2023-06-08 15:05 UTC, ericvn commented
Approve now that we have branched and this was for 1.19.

2023-06-08 15:15 UTC, merged