Remove defaultRevision - should be set in values.yaml
istio/istio.io pull request #13214
Opened 2023-05-18 15:27 UTC by jaymiracola

Setting `defaultRevision` as described does not function as intended or described (not boolean). It should be set as seen below. 
```
values:
  defaultRevision: 1-16
```

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [ X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2023-05-18 15:27 UTC, istio-testing commented
Hi @jaymiracola. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-05-19 00:12 UTC, Arhell reviewed
/ok-to-test

2023-05-19 02:12 UTC, hanxiaop commented on content/en/docs/reference/config/istio.operator.v1alpha1/index.html
> -<tr id="IstioOperatorSpec-defaultRevision">
I think this is generated and refered to the IstioOperator spec in the api repo, which should not edit here. IIRC this is not implemented and only has the api doc.

2023-05-19 12:46 UTC, ericvn requested changes
Correct. See the top of the document:
```
---
WARNING: THIS IS AN AUTO-GENERATED FILE, DO NOT EDIT. PLEASE MODIFY THE ORIGINAL SOURCE IN THE 'https://github.com/istio/api' REPO
source_repo: https://github.com/istio/api
title: IstioOperator Options
description: Configuration affecting Istio control plane installation version and shape.
```
This file is copied from the istio/api repo, and needs to be updated there.

2023-05-19 12:51 UTC, ericvn commented
Changes would be in this area: https://github.com/istio/api/blob/master/operator/v1alpha1/operator.proto#L94-L100

2023-05-30 15:29 UTC, closed without merging