help useres manage in-mesh certificates
istio/istio.io pull request #13344
Opened 2023-06-09 20:18 UTC by jacob-delgado

Help users manage in-mesh certificates. It is difficult for users to understand how to use and change these settings.

While it is environment variables

Related to https://github.com/istio/istio/pull/45382 and https://github.com/istio/istio/pull/44459 (and various other PRs)

This was a request from @costinm. See https://github.com/istio/istio/pull/44459#pullrequestreview-1406168391

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [ ] Docs
- [X] Installation
- [X] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2023-06-09 20:28 UTC, istio-testing commented
@jacob-delgado: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | e94eda20d530a41202e72b70bdfd4f39edb0e646 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/13344/lint_istio.io/1667264920040771584) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-09 20:43 UTC, istio-testing commented
@jacob-delgado: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 69b669d12f074705ffd75cd7d59ddf0731763dad | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/13344/lint_istio.io/1667269158405935104) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-09 21:04 UTC, istio-testing commented
@jacob-delgado: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 995f0cf5a1e62d72f08719827b0a9be164e9dcc7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/13344/lint_istio.io/1667273952180834304) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-12 20:14 UTC, jacob-delgado commented on content/en/docs/ops/configuration/traffic-management/manage-mesh-certificates/index.md
> +{{< tabset category-name="gateway-install-type" >}}
```suggestion
{{< tabset category-name="certificates" >}}
```

2023-07-06 12:15 UTC, windsonsea reviewed
Polish the text for easy understanding.

2023-07-06 12:15 UTC, windsonsea commented on content/en/docs/ops/configuration/traffic-management/manage-mesh-certificates/index.md
> +[pilot-agent](/docs/reference/commands/pilot-agent/) this document will only
```suggestion
[pilot-agent](/docs/reference/commands/pilot-agent/), this document will only
```

2023-07-06 12:15 UTC, windsonsea commented on content/en/docs/ops/configuration/traffic-management/manage-mesh-certificates/index.md
> +By default, the sidecars will create RSA based certificates. If the user wishes to change it to
```suggestion
By default, the sidecars will create RSA-based certificates. If you want to change it to
```

2023-07-06 12:15 UTC, windsonsea commented on content/en/docs/ops/configuration/traffic-management/manage-mesh-certificates/index.md
> +ECC then `ECC_SIGNATURE_ALGORITHM` must be set to `ECDSA`
```suggestion
ECC, you need to set `ECC_SIGNATURE_ALGORITHM` to `ECDSA`.
```

2023-07-06 12:15 UTC, windsonsea commented on content/en/docs/ops/configuration/traffic-management/manage-mesh-certificates/index.md
> +To modify the RSA key size if you wish to continue using RSA signature algorithms
```suggestion
If you prefer to retain RSA signature algorithms and want to modify the RSA key size,
```

2023-07-06 12:15 UTC, windsonsea commented on content/en/docs/ops/configuration/traffic-management/manage-mesh-certificates/index.md
> +you can change `WORKLOAD_RSA_KEY_SIZE`.
```suggestion
you can change the value of `WORKLOAD_RSA_KEY_SIZE`.
```

2023-07-06 16:10 UTC, istio-testing commented
@jacob-delgado: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 8893c0b832f3861ff114f4087a151eb81831ea9e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/13344/lint_istio.io/1676984635323584512) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-07-07 02:11 UTC, windsonsea commented
Kindly reminder: need to resolve the lint error.

2023-11-09 01:01 UTC, craigbox requested changes

2023-11-09 01:01 UTC, craigbox commented on content/en/docs/ops/configuration/traffic-management/manage-mesh-certificates/index.md
> +By default, the sidecars will create RSA-based certificates. If you want to change it to
I think this line needs `RSA-based` added to `.spelling`, and that just makes me angry.

2023-11-20 17:38 UTC, closed without merging