[zh] improve build code-blocks diagrams
istio/istio.io pull request #13369
Opened 2023-06-14 14:06 UTC by my-git9

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2023-06-14 14:16 UTC, istio-testing commented
@my-git9: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 5092515752acb8572b143b009bbba743f1b5dd90 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/13369/lint_istio.io/1668983251068260352) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-15 02:46 UTC, windsonsea reviewed
note the lint error:

```
./zh/docs/releases/contribute/diagrams/index.md:10: MD009 Trailing spaces
```

2023-06-15 02:46 UTC, windsonsea commented on content/zh/docs/releases/contribute/code-blocks/index.md
> +你可以为代码块中的内容指定语言，以实现语法高亮。上面的例子指定了语法为 `plain`，
```suggestion
您可以为代码块中的内容指定语言，以实现语法高亮。上面的例子指定了语法为 `plain`，
```

2023-06-15 02:46 UTC, windsonsea commented on content/zh/docs/releases/contribute/code-blocks/index.md
> +所有代码块的渲染结果没有任何语法高亮。但是，你可以指定其语法为 `Go`，例如：
```suggestion
所有代码块的渲染结果没有任何语法高亮。但是，您可以指定其语法为 `Go`，例如：
```
可以全局替换`你`为`您`

2023-06-15 03:44 UTC, wilsonwu commented on content/zh/docs/releases/contribute/build/index.md
> +如果您的修改没有出现编译错误，这个命令会构建这个站点，并且启动一个本地 web
```suggestion
如果您的修改没有出现编译错误，这个命令会构建这个站点，并且启动一个本地 Web
```

2023-06-15 03:44 UTC, wilsonwu commented on content/zh/docs/releases/contribute/build/index.md
> +像前面一样，可以通过 `http://192.168.7.105:1313` 这个地址来访问这个 web 服务器。
```suggestion
这个例子是在 `192.168.7.105` 这个远程服务器上构建站点并且启动一个 Web 服务器。
像前面一样，可以通过 `http://192.168.7.105:1313` 这个地址来访问这个 Web 服务器。
```

2023-06-15 03:44 UTC, wilsonwu commented on content/zh/docs/releases/contribute/code-blocks/index.md
> +如果你想为输出添加语法高亮，你可以在短代码中指定语法。在 Istio 中，最常见的例子就是
```suggestion
如果您想为输出添加语法高亮，您可以在短代码中指定语法。在 Istio 中，最常见的例子就是
```

2023-06-15 03:44 UTC, wilsonwu commented on content/zh/docs/releases/contribute/code-blocks/index.md
> +类似的，你可以从互联网动态的导入内容。使用 `url` 属性指定资源。
```suggestion
类似的，您可以从互联网动态的导入内容。使用 `url` 属性指定资源。
```

2023-06-15 03:55 UTC, istio-testing commented
@my-git9: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | e72340c3f3974f6aaae0ee16b247cc98e1fe474a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/13369/lint_istio.io/1669189747454513152) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-15 04:31 UTC, wilsonwu approved these changes
Good job, LGTM for the content, only need lint fix.

2023-06-15 04:35 UTC, wilsonwu requested changes
Miss a letter 's'

2023-06-15 04:35 UTC, wilsonwu commented on content/zh/docs/releases/contribute/diagrams/index.md
> +hape 和 style。通过本指南，您可以使用任何矢量图绘制工具（例如，Google Drawings、Inkscape、Illustrator）
```suggestion
shape 和 style。通过本指南，您可以使用任何矢量图绘制工具（例如，Google Drawings、Inkscape、Illustrator）
```

2023-06-15 06:53 UTC, windsonsea approved these changes
Thanks. LGTM

2023-06-15 07:02 UTC, merged

2023-06-15 07:03 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #13377