[zh] sync /news/support/announcing-1.16-eol/
istio/istio.io pull request #13438
Opened 2023-06-22 04:14 UTC by jiecloud

[zh] sync /news/support/announcing-1.16-eol/
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2023-06-22 04:24 UTC, istio-testing commented
@jiecloud: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | d70ab3ec4c168ee5975f29bad6ca840f45e29e24 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/13438/lint_istio.io/1671733437712568320) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-23 15:14 UTC, hanxiaop commented on content/zh/news/support/announcing-1.16-eol/index.md
> +像 1.16 这样的小版本在 N+2 小版本（在本例中为 1.18）发布后的六周内才会得到支持。
```suggestion
像 1.16 这样的小版本会在 N+2 小版本（在本例中为 1.18）发布后的六周内得到支持。
```

2023-06-24 03:11 UTC, windsonsea reviewed
url 翻译后需增加 /zh，无论是否有对应中文

不要修改 url 的 () 括号字符为全角

2023-06-24 03:11 UTC, windsonsea commented on content/zh/news/support/announcing-1.16-eol/index.md
> +根据 Istio 的 [支持政策]（/docs/releases/supported-releases#supported-releases/），
```suggestion
根据 Istio 的[支持政策](/zh/docs/releases/supported-releases#supported-releases/)，
```
不要把 url 的 () 改成汉语字符

2023-06-24 03:11 UTC, windsonsea commented on content/zh/news/support/announcing-1.16-eol/index.md
> +[Istio 1.18 于 6 月 7 日发布]（/news/releases/1.18.x/announcing-1.18/），
```suggestion
[Istio 1.18 于 6 月 7 日发布](/zh/news/releases/1.18.x/announcing-1.18/)，
```

2023-06-25 11:18 UTC, my-git9 commented on content/zh/news/support/announcing-1.16-eol/index.md
> +因此我们鼓励您升级到最新版本的 Istio ({{<istio_release_name>}})。
行尾的空格需要删除

2023-06-28 14:59 UTC, jiecloud commented on content/zh/news/support/announcing-1.16-eol/index.md
> +因此我们鼓励您升级到最新版本的 Istio ({{<istio_release_name>}})。
已修改，谢谢提醒。

2023-06-28 15:00 UTC, jiecloud commented on content/zh/news/support/announcing-1.16-eol/index.md
> +[Istio 1.18 于 6 月 7 日发布]（/news/releases/1.18.x/announcing-1.18/），
已修改，谢谢指正。

2023-06-29 02:02 UTC, windsonsea commented on content/zh/news/support/announcing-1.16-eol/index.md
> +[Istio 1.18 于 6 月 7 日发布]（/news/releases/1.18.x/announcing-1.18/），
额，没改呀，这 url 还是错的 -_!

2023-06-30 13:41 UTC, istio-testing commented
@jiecloud: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 1a9e70cec77ce8109c6b1c3e367c747a42cc91be | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/13438/lint_istio.io/1674772343899033600) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-07-01 07:06 UTC, my-git9 requested changes

2023-07-01 07:06 UTC, my-git9 commented on content/zh/news/support/announcing-1.16-eol/index.md
> +[Istio 1.18 于 6 月 7 日发布]（/zh/news/releases/1.18.x/announcing-1.18/），
```suggestion
[Istio 1.18 于 6 月 7 日发布](/zh/news/releases/1.18.x/announcing-1.18/)，
```

2023-07-04 00:50 UTC, windsonsea approved these changes
LGTM now.

If you have changed based on the suggested comments, you can click `Resolve conversation`, so each reviewer can easily know the PR progress.

2023-07-04 00:51 UTC, merged

2023-07-04 00:53 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #13502