[zh] sync/news/security/istio-security-2020-004
istio/istio.io pull request #13449
Opened 2023-06-23 19:01 UTC by huan555

Sync with en text

- [x] Docs

2023-06-23 19:01 UTC, istio-testing commented
Hi @huan555. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-06-23 19:24 UTC, ericvn commented
/ok-to-test

2023-06-23 19:26 UTC, istio-testing commented
@huan555: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | dac794c65b89d862501fedc5f04476d3b6c81551 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/13449/lint_istio.io/1672324801718390784) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-23 19:58 UTC, istio-testing commented
@huan555: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 3dc1865cb088a51ece75f29658ddfa6ce85b6cb6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/13449/lint_istio.io/1672332936097042432) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-24 03:02 UTC, windsonsea commented
/ok-to-test

2023-06-24 03:03 UTC, istio-testing commented
@huan555: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 3dc1865cb088a51ece75f29658ddfa6ce85b6cb6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/13449/lint_istio.io/1672440009182941184) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-06-24 03:12 UTC, windsonsea commented
让自己的每个 commit 都有意义，不要这样滥用

2023-06-24 08:42 UTC, zirain requested changes
These informations is out of date for a long time, I feel meaningless to translate them.

2023-06-25 02:08 UTC, huan555 commented
> 
ok， I will close it

2023-06-25 02:08 UTC, closed without merging