move Telemetry API to alpha
istio/istio.io pull request #13585
Opened 2023-07-18 01:23 UTC by zirain

Please provide a description for what this PR is for.

xref: https://github.com/istio/enhancements/pull/145

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [x] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2023-07-18 01:40 UTC, dhawton requested changes

2023-07-18 01:40 UTC, dhawton commented on content/en/docs/tasks/observability/telemetry/index.md
>  status: Experimental
```suggestion
status: Alpha
```

2023-07-18 02:00 UTC, zirain commented on content/en/docs/tasks/observability/telemetry/index.md
>  status: Experimental
done

2023-07-18 03:13 UTC, dhawton approved these changes

2023-07-18 03:24 UTC, merged

2023-07-19 08:19 UTC, zirain commented
/cherrypick release-1.18

2023-07-19 09:12 UTC, craigbox commented
Not even Beta yet? 🤣