fix spelling error
istio/istio.io pull request #13674
Opened 2023-08-01 12:08 UTC by weizhoublue

fix spelling error

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2023-08-01 12:08 UTC, istio-testing commented
Hi @weizhoublue. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2023-08-01 13:00 UTC, ericvn commented on content/en/docs/setup/upgrade/_index.md
> +description: Upgrade, downgrade, and manage Istio across multiple control plane revisions.
This is the only change that is in this repo, so this PR will likely be this one file.

2023-08-01 13:17 UTC, ericvn requested changes
Need to remove a number of changes, as they need to be done in other files.

2023-08-01 13:27 UTC, weizhoublue commented on content/en/docs/reference/commands/install-cni/index.html
> +<td>The UDS server address which CNI plugin will copy log output to  (default `/var/run/istio-cni/log.sock`)</td>
got it , thanks for the reminding

2023-08-02 03:33 UTC, weizhoublue commented
I will open another PR

2023-08-02 03:33 UTC, closed without merging

2023-08-04 18:56 UTC, ericvn commented
I see you created https://github.com/istio/istio/pull/46276 to handle some of the spelling corrections. Are you planning to create the other two PRs based on the changes above? Else I can create the PRs (and make you a co-committer if I know your email).

2023-08-04 19:14 UTC, ericvn commented
I found your email so made you a co-commiter on the changes in the other repos. Thanks again for these.

2023-08-05 16:28 UTC, weizhoublue commented
> I found your email so made you a co-commiter on the changes in the other repos. Thanks again for these.

@ericvn  sorry for my late reply. I see https://github.com/istio/istio.io/pull/13691 and many thanks