For 1.20, drop requirement to have a Service associated with a pod
istio/istio.io pull request #13717
Opened 2023-08-10 20:23 UTC by howardjohn

Fixed in https://github.com/istio/istio/pull/46295

2023-08-10 23:28 UTC, dhawton approved these changes

2023-08-11 01:33 UTC, ericvn commented
Since you mention 1.20, we will need to wait to merge this until after we branch at the 1.19.0 release.

2023-08-14 13:03 UTC, ericvn requested changes
Currently the master branch for istio.io is for the 1.19 release (until we branch it on release day. Hold this PR until then.

2023-09-05 21:44 UTC, ericvn approved these changes

2023-09-05 22:03 UTC, dhawton commented
Removed DNM as master is 1.20

2023-09-05 22:15 UTC, merged