update hugo to 0.120.3
istio/istio.io pull request #14098
Opened 2023-11-05 22:25 UTC by Arhell

resolve https://github.com/istio/istio.io/issues/14094
Let me know when the thread can be updated branch.

2023-11-08 23:42 UTC, craigbox requested changes

2023-11-08 23:42 UTC, craigbox commented on netlify.toml
> +    HUGO_VERSION = "0.120.3"
```suggestion
    HUGO_VERSION = "0.120.4"
```

2023-11-09 00:07 UTC, Arhell commented on netlify.toml
> +    HUGO_VERSION = "0.120.3"
Thank you, already

2023-11-10 15:33 UTC, ericvn commented
Just adding the DNM label to be removed once we have branched.

2023-11-16 14:33 UTC, ericvn approved these changes
LGTM, and we have branched.

2023-11-16 18:14 UTC, craigbox commented
LGTM!

2023-11-16 18:26 UTC, merged