Update CEL documentation to capture type checking errors.
istio/istio.io pull request #14107
Opened 2023-11-06 18:27 UTC by whitneygriffith

Part of [#47533](https://github.com/istio/istio/issues/47533) 

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [x] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

2023-11-06 18:30 UTC, istio-testing commented
@whitneygriffith: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_istio.io | bcdcd8312211b6aea0fdbf9aea785342551b7679 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/14107/gencheck_istio.io/1721595192382853120) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-11-06 18:37 UTC, istio-testing commented
@whitneygriffith: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
gencheck_istio.io | bcdcd8312211b6aea0fdbf9aea785342551b7679 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/14107/gencheck_istio.io/1721595192382853120) | true | `/test gencheck`
lint_istio.io | bcdcd8312211b6aea0fdbf9aea785342551b7679 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/14107/lint_istio.io/1721595192332521472) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-11-06 18:53 UTC, dhawton requested changes
Also make sure you run `make gen` which will generate a test for the code snippet you added.

2023-11-06 18:53 UTC, dhawton commented on content/en/docs/tasks/observability/logs/telemetry-api/index.md
> +    The following configuration displays access logs only when the logs aren't generated by the Amazon-Route53-Health-Check-Service.
```suggestion
    The following configuration displays access logs only when the logs aren't generated by the Amazon-Route53-Health-Check-Service.
```

2023-11-06 18:53 UTC, dhawton commented on content/en/docs/tasks/observability/logs/telemetry-api/index.md
> +    EOF
```suggestion
          expression: "!has(request.useragent) || !(request.useragent.startsWith("Amazon-Route53-Health-Check-Service"))"
    EOF
```

2023-11-06 19:23 UTC, istio-testing commented
@whitneygriffith: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 5365b840c686331cdc6f89686f3fd12ba6ddff11 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/14107/lint_istio.io/1721607336105086976) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-11-07 17:00 UTC, istio-testing commented
@whitneygriffith: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 823236f309763ecadc257e4424795a55847d666b | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/14107/lint_istio.io/1721932896513560576) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-11-08 20:38 UTC, istio-testing commented
@whitneygriffith: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 3499c5ed74e7ea71f8df125c3f6780fbb5d47ddb | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/14107/lint_istio.io/1722350216092323840) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-11-08 23:40 UTC, craigbox requested changes

2023-11-08 23:40 UTC, craigbox commented on content/en/docs/tasks/observability/logs/telemetry-api/index.md
> +    The following configuration displays access logs only when the logs are not generated by the Amazon Route53 Health Check Service.
```suggestion
    The following configuration displays access logs only when the logs are not generated by the Amazon Route 53 Health Check Service.
```

That will fix the final lint error.

2023-11-10 15:32 UTC, ericvn commented
It might be beneficial to add a call to your snippet in the test.sh to verify that the snippet is good. Verifying the behavior is correct would also be beneficial, but noting we don't have user-agent in the util at this point.

2023-11-13 15:23 UTC, whitneygriffith commented
> It might be beneficial to add a call to your snippet in the test.sh to verify that the snippet is good. Verifying the behavior is correct would also be beneficial, but noting we don't have user-agent in the util at this point.

I am trying decide if it's worth implementing user-agent in the util. I know the snippet works based on user feedback here [#47533](https://github.com/istio/istio/issues/47533). If you think its worth it Ii will implement it.

2023-11-13 19:36 UTC, ericvn commented
> @ericvn I am trying decide if it's worth implementing user-agent in the util. I know the snippet works based on user feedback here [#47533](https://github.com/istio/istio/issues/47533). If you think it's worth it Ii will implement it.

@whitneygriffith to get the change in quicker we can probably ignore the test for right now. I notice the earlier bullet was added without a test as well. We could open an issue for someone to add tests for the two bullets (and maybe other missed items if there are any).

2023-11-13 19:37 UTC, ericvn approved these changes

2023-11-14 01:10 UTC, dhawton approved these changes

2023-11-15 23:21 UTC, craigbox approved these changes

2023-11-15 23:36 UTC, merged