Announcing Izzy - Istio's CNCF Phippy family Character
istio/istio.io pull request #14710
Opened 2024-03-08 20:48 UTC by kfaseela

2024-03-08 20:50 UTC, kfaseela commented
Adding a dnm so that this can be published at the right time

2024-03-08 21:05 UTC, keithmattix approved these changes
LGTM!

2024-03-08 21:11 UTC, linsun approved these changes

2024-03-08 21:11 UTC, linsun commented
Thanks Faseela!

2024-03-09 00:07 UTC, craigbox commented
https://deploy-preview-14710--preliminary-istio.netlify.app/latest/blog/2024/istio-phippy/

2024-03-09 00:12 UTC, craigbox requested changes

2024-03-09 00:12 UTC, craigbox commented on content/en/blog/2024/istio-phippy/index.md
> +description: Announcing Istio's new Phippy character.
```suggestion
title: "Istio joins Phippy and friends — Welcome Izzy!"
description: Announcing the latest member of the CNCF family of mascots.
```
to not say "Phippy" twice

2024-03-10 07:08 UTC, kfaseela commented
@craigbox if the PR looks good now, you can approve. I will remove the dnm at the announcement time

2024-03-10 07:10 UTC, craigbox approved these changes
LGTM, thanks!

2024-03-11 01:25 UTC, kebe7jun approved these changes

2024-03-11 13:03 UTC, ericvn commented on content/en/blog/2024/istio-phippy/index.md
> +Istio stands on the shoulders of several other CNCF projects, including Kubernetes, Envoy, Prometheus, and Helm. Izzy is proud to join Phippy, Hazel and Captain Kube’s gang, taking cloud native to th
Inconsistent Oxford comma?
```suggestion
Istio stands on the shoulders of several other CNCF projects, including Kubernetes, Envoy, Prometheus, and Helm. Izzy is proud to join Phippy, Hazel, and Captain Kube’s gang, taking cloud native to the masses.
```

2024-03-11 14:12 UTC, ericvn approved these changes

2024-03-11 16:14 UTC, irisdingbj approved these changes

2024-03-11 21:16 UTC, craigbox commented on content/en/blog/2024/istio-phippy/index.md
> +Istio stands on the shoulders of several other CNCF projects, including Kubernetes, Envoy, Prometheus, and Helm. Izzy is proud to join Phippy, Hazel and Captain Kube’s gang, taking cloud native to th
❤️ 🔥

2024-03-12 04:51 UTC, kfaseela commented
/cherrypick release-1.20

2024-03-12 04:51 UTC, istio-testing commented
@kfaseela: once the present PR merges, I will cherry-pick it on top of release-1.20 in a new PR and assign it to you.

<details>

In response to [this](https://github.com/istio/istio.io/pull/14710#issuecomment-1990396499):

>/cherrypick release-1.20


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2024-03-12 05:03 UTC, merged

2024-03-12 05:05 UTC, istio-testing commented
@kfaseela: new pull request created: #14727

<details>

In response to [this](https://github.com/istio/istio.io/pull/14710#issuecomment-1990396499):

>/cherrypick release-1.20


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2024-03-13 07:35 UTC, Charley-Mann commented
Hey folks FYI we are ready and set with the CNCF blog announcement for 09:00 PST today (March 13), as well as follow-up social media posts ^ @kfaseela

2024-03-13 07:38 UTC, kfaseela commented
> Hey folks FYI we are ready and set with the CNCF blog announcement for 09:00 PST today (March 13), as well as follow-up social media posts ^ @kfaseela 

Hello Charley, looks like the blog was already published yesterday.. Daniel crook sent me the link https://www.cncf.io/blog/2024/03/11/istio-joins-phippy-and-friends-welcome-izzy/