update hugo to v0.133.0
istio/istio.io pull request #15553
Opened 2024-08-13 21:19 UTC by Arhell

resolve https://github.com/istio/istio.io/issues/15548

2024-08-14 03:19 UTC, dhawton requested changes
https://github.com/istio/tools/blob/release-1.23/docker/build-tools/Dockerfile#L59

We should keep this in sync with the build-tools.

2024-08-20 03:20 UTC, craigbox approved these changes

2024-08-20 04:08 UTC, dhawton commented
https://github.com/istio/tools/pull/3013 should merge first so we don't get too far ahead of the tooling

2024-08-20 16:05 UTC, dhawton approved these changes

2024-08-20 16:16 UTC, merged