1.22.4 Release Notes
istio/istio.io pull request #15570
Opened 2024-08-18 13:43 UTC by zirain

2024-08-18 13:51 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | dd571a427c89114e79ec3c71b8c6066afdc59cb5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/15570/lint_istio.io/1825166556691173376) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-08-18 13:55 UTC, wilsonwu commented on content/en/news/releases/1.22.x/announcing-1.22.4/index.md
> +which has an `Ingress` object or a `gateway.networking.k8s.io` `Gateway` object, moves from being selected to unselected.
```suggestion
- **Fixed** an issue that can trigger a deadlock when `discoverySelectors` (configured in `MeshConfig`) and a namespace,
  which has an `Ingress` object or a `gateway.networking.k8s.io` `Gateway` object, moves from being selected to unselected.
```

2024-08-18 15:15 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 1725b90e1f3c598f805d44bd282a8a7f7258ccd7 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/15570/lint_istio.io/1825187989693665280) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-08-18 18:49 UTC, dhawton requested changes

2024-08-18 18:49 UTC, dhawton commented on content/en/news/releases/1.22.x/announcing-1.22.4/index.md
> +  ([Issue #52218](https://github.com/istio/istio/issues/52218))
```suggestion
- **Fixed** handling of a a failure adding a pod to the dataplane where the pod was still added to ipset.
  ([Issue #52218](https://github.com/istio/istio/issues/52218))
```

2024-08-18 18:49 UTC, dhawton commented on content/en/news/releases/1.22.x/announcing-1.22.4/index.md
> +- **Fixed** an omission in ztunnel helm charts which resulted in some Kubernetes resources being created without labels
```suggestion
- **Fixed** an omission in ztunnel helm charts which resulted in some Kubernetes resources being created without labels.
```

2024-08-18 18:49 UTC, dhawton commented on content/en/news/releases/1.22.x/announcing-1.22.4/index.md
> +which has an `Ingress` object or a `gateway.networking.k8s.io` `Gateway` object, moves from being selected to unselected.
```suggestion
- **Fixed** an issue that can trigger a deadlock when `discoverySelectors` (configured in `MeshConfig`) and a namespace,
  which has an `Ingress` object or a Kubernetes `Gateway` object, would move from being selected to unselected.
```

2024-08-18 18:49 UTC, dhawton commented on content/en/news/releases/1.22.x/announcing-1.22.4/index.md
> +- **Removed** writing the experimental field `GatewayClass.status.supportedFeatures`, as it is unstable in the API.
```suggestion
- **Removed** writing the experimental field `GatewayClass.status.supportedFeatures`, as it was unstable in the API.
```

2024-08-18 18:50 UTC, dhawton commented on content/en/news/releases/1.22.x/announcing-1.22.4/index.md
> +- **Fixed** VirtualMachine WorkloadEntry locality label missing during autoregistration.
```suggestion
- **Fixed** an issue where the `VirtualMachine` `WorkloadEntry` locality label was missing during auto-registration.
```

2024-08-18 18:51 UTC, dhawton commented on content/en/news/releases/1.22.x/announcing-1.22.4/index.md
> +- **Fixed** matching multiple service VIPs in ServiceEntry.
```suggestion
- **Fixed** matching multiple service VIPs in `ServiceEntry`.
```

2024-08-18 23:48 UTC, istio-testing commented
@zirain: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
lint_istio.io | 99de9c37fe81ba94418ce9af612fb31c645514b8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/15570/lint_istio.io/1825316556960174080) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2024-08-19 04:12 UTC, craigbox commented on content/en/news/releases/1.22.x/announcing-1.22.4/index.md
> +- **Fixed** matching multiple service VIPs in `ServiceEntry`.
```suggestion
- **Fixed** a case where listeners were missing for addresses beyond the first in a `ServiceEntry`.
```

2024-08-19 04:13 UTC, craigbox commented on content/en/news/releases/1.22.x/announcing-1.22.4/index.md
> +- **Fixed** matching multiple service VIPs in `ServiceEntry`.
this is a nit you can easily ignore

2024-08-19 04:14 UTC, craigbox approved these changes

2024-08-19 16:42 UTC, dhawton approved these changes

2024-08-19 16:43 UTC, dhawton commented
Good to merge when you're ready. The cherrypick will need approval/hold until publish.

2024-08-19 19:51 UTC, merged

2024-08-19 19:53 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #15573