Clarify subjectAltNames requires tls mode MUTUAL
istio/istio.io pull request #15733
Opened 2024-09-26 06:38 UTC by zioproto

## Description

The user might be confused about the usage of `subjectAltNames`, trying to use it to add more hostnames to an endpoint.
Make clear that it requires TLS mode mutual, and the the alternative names are those presented by the client for authentication.

## Reviewers

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

2024-09-26 06:38 UTC, istio-testing commented
Hi @zioproto. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository.
</details>

2024-09-26 07:51 UTC, wilsonwu commented
/ok-to-test

2024-09-26 13:50 UTC, nshankar13 commented on content/en/docs/reference/config/networking/gateway/index.html
> +certificate presented by the client. Requires tls mode MUTUAL.</p>
Nit - "requires TLS mode to be set to MUTUAL" ?

2024-09-26 15:19 UTC, dhawton requested changes
```
WARNING: THIS IS AN AUTO-GENERATED FILE, DO NOT EDIT. PLEASE MODIFY THE ORIGINAL SOURCE IN THE 'https://github.com/istio/api' REPO
```

This needs to be changed in the api repo.

2024-10-03 07:40 UTC, zioproto commented
@dhawton can you help me to understand where to patch exactly ?

I found here:
https://github.com/istio/api/blob/eb7df4d4b474d2aa19f89fcece31c60893a7eb67/networking/v1alpha3/gateway.pb.html#L542-L547

but that also seems to be generated.

Do I have to patch the `.go` file here in the `v1alpha3` folder ?
https://github.com/istio/api/blob/eb7df4d4b474d2aa19f89fcece31c60893a7eb67/networking/v1alpha3/gateway.pb.go#L789-L790

Also the `v1beta1` and `v1` API folders seem not to have the full `gateway.pb.go` file. I am not familiar with this repo. Could you please advice ? thanks

2024-10-03 14:24 UTC, dhawton commented
It comes from the proto files, that's where you'll need to edit it. The `.pb.go` files are generated from the protos, and the docs are also generated from the protos.

2024-10-03 15:02 UTC, closed without merging

2024-10-03 15:02 UTC, zioproto commented
Closing in favour of https://github.com/istio/api/pull/3319