Add more details to security disclosure page
istio/istio.io pull request #8228
Opened 2020-09-29 19:41 UTC by howardjohn

Attempt to get people to stop publicly filing security vulns in github

2020-09-29 19:41 UTC, howardjohn commented
https://github.com/istio/istio/pull/27627 is related

2020-09-29 19:43 UTC, ericvn commented on content/en/about/security-vulnerabilities/index.md
> +* Any potentional Denial Of Service (DoS)
c/Of/of

2020-09-29 19:47 UTC, istio-testing commented
@howardjohn: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | a04de04f01aa8058c55239a5ec214083d52ff6c6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8228/lint_istio.io/8617) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-09-29 19:48 UTC, fpesce requested changes

2020-09-29 19:48 UTC, fpesce commented on content/en/about/security-vulnerabilities/index.md
> +* Any potentional Denial Of Service (DoS)
```suggestion
* Any potential Denial of Service (DoS)
```

2020-09-29 19:50 UTC, nrjpoddar commented on content/en/about/security-vulnerabilities/index.md
> +* Any security policy bypass or weakness
```suggestion
* Any security policy (like Authentication or Authorization) bypass or weakness
```

2020-09-29 20:51 UTC, ericvn approved these changes

2020-09-29 21:31 UTC, fpesce approved these changes

2020-09-30 15:57 UTC, howardjohn commented
/test gencheck_istio.io

2020-09-30 16:08 UTC, merged

2020-09-30 16:08 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #8239