Add regex matching semantics documentation
istio/istio.io pull request #8340
Opened 2020-10-22 21:08 UTC by xulingqing

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2020-10-22 21:13 UTC, istio-testing commented
@xulingqing: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 7205aff435a3dcd8675087848a188757b9e6eb02 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8340/lint_istio.io/8877) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-22 21:45 UTC, istio-testing commented
@xulingqing: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 99c2341a8874b53e12a803a5c6044ca610295c2c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8340/lint_istio.io/8878) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-23 03:33 UTC, istio-testing commented
@xulingqing: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 91decdfafd17a3d09dd84a7519c6ca6865b5b0ea | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8340/lint_istio.io/8879) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-23 05:13 UTC, istio-testing commented
@xulingqing: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 90bc6fdc4760dc6e52b4c33ccec19e3edeb8cee8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8340/lint_istio.io/8880) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-23 05:43 UTC, istio-testing commented
@xulingqing: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 90bc6fdc4760dc6e52b4c33ccec19e3edeb8cee8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8340/lint_istio.io/8880) | `/test lint_istio.io`
doc.test.profile_none_istio.io | 90bc6fdc4760dc6e52b4c33ccec19e3edeb8cee8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8340/doc.test.profile_none_istio.io/434) | `/test doc.test.profile_none_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-23 05:59 UTC, istio-testing commented
@xulingqing: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 90bc6fdc4760dc6e52b4c33ccec19e3edeb8cee8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8340/lint_istio.io/8880) | `/test lint_istio.io`
doc.test.profile_none_istio.io | 90bc6fdc4760dc6e52b4c33ccec19e3edeb8cee8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8340/doc.test.profile_none_istio.io/434) | `/test doc.test.profile_none_istio.io`
doc.test.profile_default_istio.io | 90bc6fdc4760dc6e52b4c33ccec19e3edeb8cee8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8340/doc.test.profile_default_istio.io/433) | `/test doc.test.profile_default_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-26 14:34 UTC, frankbu commented on content/en/docs/concepts/security/index.md
>     that a field must be present, use the `fieldname: ["*"]`format. This is
```suggestion
   that a field must be present, use the `fieldname: ["*"]` format. This is
```

2020-10-26 14:46 UTC, frankbu commented on content/en/docs/concepts/security/index.md
> +- Regex match: `"regex:"` is used as special prefix. Anything after "regex:" is
```suggestion
- Regex match: If a string begins with `regex:`, the following text is 
```

2020-10-26 14:47 UTC, frankbu commented on content/en/docs/concepts/security/index.md
> +   interpreted as regular expression. For example, `'regex:abc.com\/[0-9]?'`
```suggestion
   interpreted as a regular expression. For example, `'regex:abc.com\/[0-9]?'`
```

2020-10-26 19:19 UTC, yangminzhu requested changes
This feature is disabled by default and requires to set a flag to opt-in, so it shouldn't be documented in the concept page as if it's the default behavior.

Instead I suggest to move the changes to be a new section in https://istio.io/latest/docs/tasks/security/authorization/authz-http/#configure-access-control-for-workloads-using-http-traffic, and add instructions about how to set the flag to test it.

Also putting this on hold as it is not in 1.8, should not be merged before 1.8 is released.

2020-10-26 19:24 UTC, xulingqing commented
> This feature is disabled by default and requires to set a flag to opt-in, so it shouldn't be documented in the concept page as if it's the default behavior.
> 
> Instead I suggest to move the changes to be a new section in https://istio.io/latest/docs/tasks/security/authorization/authz-http/#configure-access-control-for-workloads-using-http-traffic, and add instructions about how to set the flag to test it.
> 
> Also putting this on hold as it is not in 1.8, should not be merged before 1.8 is released.

Sure, willdo. Thanks!

2020-10-27 15:07 UTC, frankbu commented
Closing for now. @xulingqing please reopen or send a new PR when its ready to be merged.

2020-10-27 15:07 UTC, closed without merging