Fix Documentation on MetricConfig field: tagsToRemove
istio/istio.io pull request #8966
Opened 2021-02-12 15:59 UTC by crhuber

Fixes Documentation on MetricConfig field: tagsToRemove.
Currently if you configure your manifest file with tagsToRemove, it has no effect on the tags that are removed by Istio-proxy ie:

has no effect on tags:
```
    telemetry:
      enabled: true
      v1:
        enabled: false
      v2:
        enabled: true
        prometheus:
          configOverride:
            inboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                - name: requests_total
                  tagsToRemove: ["destination_principal", "source_principal"]
```

However, this works:

```
    telemetry:
      enabled: true
      v1:
        enabled: false
      v2:
        enabled: true
        prometheus:
          configOverride:
            inboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                - name: requests_total
                  tags_to_remove: ["destination_principal", "source_principal"]
```

This PR updates the documentation to reflect that `tags_to_remove` is the correct field name

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2021-02-12 15:59 UTC, istio-testing commented
Hi @crhuber. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-02-12 16:00 UTC, crhuber commented
@googlebot I signed it!

2021-02-12 16:10 UTC, ericvn requested changes

2021-02-12 16:10 UTC, ericvn commented on content/en/docs/reference/config/proxy_extensions/stats/index.html
> +<td><code>tags_to_remove</code></td>
This change comes from a file in another repo. Making the change here will be overwritten the next day.

I think the update might need to be here: https://github.com/istio/proxy/blob/master/extensions/stats/config.proto#L44

2021-02-12 16:14 UTC, ericvn commented on content/en/docs/reference/config/proxy_extensions/stats/index.html
> +<td><code>tags_to_remove</code></td>
I believe that comes from here: https://github.com/istio/proxy/blob/master/extensions/stats/config.proto#L44

I don'r know enough about the generation from the .proto to the .pb.html.

2021-02-12 18:59 UTC, bianpengyuan commented
https://github.com/istio/proxy/pull/3191 should supersede this.

2021-02-12 22:04 UTC, ericvn commented
https://github.com/istio/proxy/pull/3191 does have a change for the master branch which will update preliminary.istio.io. I did ask about cherrypicking it back to 1.9 which will fix istio.io (at least latest).

2021-02-17 17:53 UTC, ericvn commented
Closing this PR as istio/proxy#3191 should fix the problem and it is incorrect to fix in this repo.

2021-02-17 17:53 UTC, closed without merging