Submitting a blog about IstioCon program
istio/istio.io pull request #8969
Opened 2021-02-12 19:40 UTC by macruzbar

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2021-02-12 19:41 UTC, istio-testing commented
Hi @macruzbar. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-02-12 20:18 UTC, ericvn commented
/ok-to-test

2021-02-12 20:19 UTC, istio-testing commented
@macruzbar: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 6755d5d9e49cea88d40e54fad18ccb64f9d77a7c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8969/lint_istio.io/1360322397151956992) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-12 20:20 UTC, ericvn commented on content/en/blog/2021/istiocon-2021-program/.spelling.md
> +# markdown-spellcheck spelling configuration file
We typically use the .spelling in the root directory of the repo.

2021-02-12 22:51 UTC, istio-testing commented
@macruzbar: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 79fe2cbca90a12ec321bf2a11c036f151fc87a97 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8969/lint_istio.io/1360360751084081152) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-12 23:55 UTC, istio-testing commented
@macruzbar: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 22ec80850b9ebd26351f785e64068524ca1e0aa0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8969/lint_istio.io/1360375293893677056) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-13 03:16 UTC, nrjpoddar commented
I would recommend adding a blurb about Istio 2021 roadmap if you can.

2021-02-15 12:27 UTC, craigbox requested changes
`content/en/blog/2020/istioconlogo.jpg` => that should be 2021?  It doesn't appear to be used anyway, so you may wish to remove it.

(I can't see the preview sorry, I've pinged Docs WG on Slack to see why that is)

2021-02-15 12:28 UTC, craigbox commented on content/en/blog/2021/istiocon-2021-program/index.md
> +publishdate: 2020-02-12
```suggestion
publishdate: 2021-02-16
```

2021-02-16 15:44 UTC, frankbu commented
This PR seems time sensitive, so I quickly fixed it up in #8983.

2021-02-16 15:44 UTC, closed without merging