Announce EOL for Istio 1.7
istio/istio.io pull request #9005
Opened 2021-02-19 06:28 UTC by JimmyCYJ

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2021-02-19 13:26 UTC, craigbox requested changes
I don't think you want the first four commits, which adds a 1.7.7 release note which is already in the tree.

2021-02-23 22:06 UTC, ericvn approved these changes

2021-02-24 20:14 UTC, craigbox approved these changes

2021-02-25 20:27 UTC, merged

2021-02-25 20:28 UTC, istio-testing commented
In response to a cherrypick label: #9005 failed to apply on top of branch "release-1.9":
```
Applying: Release notes for 1.7.7
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
CONFLICT (add/add): Merge conflict in content/en/news/releases/1.7.x/announcing-1.7.7/index.md
Auto-merging content/en/news/releases/1.7.x/announcing-1.7.7/index.md
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Release notes for 1.7.7
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

2021-02-25 20:28 UTC, istio-testing commented
In response to a cherrypick label: new issue created for failed cherrypick: #9065