Add content to the security doc around hardening based on a previousl…
istio/istio.io pull request #9095
Opened 2021-03-02 19:47 UTC by jacob-delgado

…y disclosed cve

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2021-03-02 19:48 UTC, istio-testing commented
@jacob-delgado: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | c23209a58793c5b37be95932979f71103d9b35d6 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9095/lint_istio.io/1366837688434429952) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-02 19:59 UTC, brian-avery commented on content/en/docs/ops/best-practices/security/index.md
> +1. Create a config map by downloading [custom-bootstrap-runtime.yaml](/news/security/istio-security-2020-007/custom-bootstrap-runtime.yaml). Update `global_downstream_max_connections` in the config m
I would prefer a link instead of the long-form instructions here. That said, if we're going to use long-form instructions, should we use a snippet shared between the doc and the security announcement?

2021-03-02 20:08 UTC, rvennam commented
This new section feels out of place from the rest of the document. The document is meant to provide high level best practices with explanations and recommendations. The new section comes in right at the top and is a workaround for a specific vulnerability. I'm wondering if there is not a better place for this. @istio/wg-docs-maintainers-english

2021-03-02 20:10 UTC, craigbox commented
> I'm wondering if there is not a better place for this. 

I agree; maybe this setting should just become default if that's sensible?

2021-03-02 20:39 UTC, jacob-delgado commented
> > I'm wondering if there is not a better place for this. 
> 
> 
> 
> I agree; maybe this setting should just become default if that's sensible?
> 
> 


It's break glass. It'll cause a lot of headaches as the value depends on the user's environment so there's no reasonable default that would work. The concern from the PSWG is that people aren't applying this patch or are not aware of it.

2021-03-03 01:08 UTC, jacob-delgado commented
> This new section feels out of place from the rest of the document. The document is meant to provide high level best practices with explanations and recommendations. The new section comes in right at the top and is a workaround for a specific vulnerability. I'm wondering if there is not a better place for this. @istio/wg-docs-maintainers-english

My take is that the document is still a work in progress. I like that we have it in place, as many users weren't aware of these issues, but there are no examples in how to configure or change settings. For people new to Istio it currently is a burden to understand how to enable/toggle features on or off based on the Product Security WG's recommendations.

I hope that the PSWG will be able to make this page more user friendly in the near future. This is one example of what we'd want to do.

2021-03-03 01:12 UTC, istio-testing commented
@jacob-delgado: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 67a61690c5a1087d4bf949ad7225e802d4fc463f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9095/lint_istio.io/1366919177167704064) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-03 01:13 UTC, jacob-delgado commented on content/en/docs/ops/best-practices/security/index.md
> +1. Create a config map by downloading [custom-bootstrap-runtime.yaml](/news/security/istio-security-2020-007/custom-bootstrap-runtime.yaml). Update `global_downstream_max_connections` in the config m
Added a boilerplate. I'm not sure I'm convinced we shouldn't give users more info to change things and enable/disable features without examples. This guide shouldn't be a burden for users to adopt long-term.

2021-03-03 01:13 UTC, istio-testing commented
@jacob-delgado: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 67a61690c5a1087d4bf949ad7225e802d4fc463f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9095/lint_istio.io/1366919177167704064) | `/test lint_istio.io`
gencheck_istio.io | 67a61690c5a1087d4bf949ad7225e802d4fc463f | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9095/gencheck_istio.io/1366919177192869888) | `/test gencheck_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-03 01:20 UTC, istio-testing commented
@jacob-delgado: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | aa147d303fcf93b99e052e0d05074f81a95edec8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9095/lint_istio.io/1366920650907717632) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-13 23:08 UTC, brian-avery commented
Any chance that we can continue moving this forward? We do have users who assume that because they are running the latest release of Istio, all of the vulnerabilities with fixes released before that version are fixed without any intervention needed on their part. Unfortunately, in instances like this, that's not always possible as the solution varies depending on their environment. I'm ok with us putting this information somewhere else, but right now we have users running Istio in vulnerable configurations and I think we need to find a way to highlight that.

2021-04-27 18:45 UTC, brian-avery commented on content/en/docs/ops/best-practices/security/index.md
> +## Envoy Downstream Connections
@jacob-delgado From a conversation offline with @craigbox:

* Can we move this further down the page? 
* Can we rename it to "Configure a limit on downstream connections"
* Can we add some context on why users want to limit the number of connections they support?

2021-04-27 18:49 UTC, brian-avery commented on content/en/docs/ops/best-practices/security/index.md
> +In [Security Bulletin 2020-007](/news/security/istio-security-2020-007/) it was disclosed that [CVE-2020-8663](https://nvd.nist.gov/vuln/detail/CVE-2020-8663)
Adding this and we can massage from there: 

```suggestion
From [Security Bulletin 2020-007](/news/security/istio-security-2020-007/), Istio by default has no limit on the number of connections that it supports. This means that connections may continue being created until the host runs out of resources and the ingress gateway crashes, causing a denial of service. Due to the vast difference between the way that different users use Istio, this must be configured individually for your environment. 
```

2021-04-27 18:52 UTC, craigbox reviewed
try this order of thoughts: "By default, Istio (and Envoy) have no limit on the number of xxx.  This can be exploited by a malicious actor (see security bulletin yyy).  To work around you do zzz"

2021-04-27 19:01 UTC, brian-avery commented on content/en/boilerplates/cve-2020-007-configmap.md
> +CVE-2020-8663 is addressed in Envoy by adding a configurable limit on [downstream connections](https://www.envoyproxy.io/docs/envoy/v1.14.3/configuration/operations/overload_manager/overload_manager#
Lets move this top paragraph back and keep the steps in the boilerplate

2021-04-27 19:02 UTC, brian-avery commented on content/en/docs/ops/best-practices/security/index.md
> +In [Security Bulletin 2020-007](/news/security/istio-security-2020-007/) it was disclosed that [CVE-2020-8663](https://nvd.nist.gov/vuln/detail/CVE-2020-8663)
```suggestion
By default, Istio (and Envoy) have no limit on the number of downstream connections. This can be exploited by a malicious actor (see [security bulletin 2020-007](/news/security/istio-security-2020-007/)). To work around you this, you must configure an appropriate connection limit for your environment.
```

2021-04-27 20:19 UTC, istio-testing commented
@jacob-delgado: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | b881dc27d3a342cb4f2b4cf99e156b1f4d9378fe | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9095/lint_istio.io/1387138335507484672) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-27 20:23 UTC, brian-avery commented on content/en/docs/ops/best-practices/security/index.md
> +needed additional configuration to mitigate the issue. This is a break glass change that cannot be changed in Istio
```suggestion
```

2021-04-27 20:23 UTC, brian-avery commented on content/en/docs/ops/best-practices/security/index.md
> +without affecting users.
```suggestion

```

2021-04-27 20:23 UTC, istio-testing commented
@jacob-delgado: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 5bb6f9bc78e86b3e0b41c5ec61de0aff7e2598bd | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9095/lint_istio.io/1387139630737920000) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-28 14:15 UTC, brian-avery commented on content/en/boilerplates/snips/cve-2020-007-configmap.sh
> +kubectl --namespace istio-system exec -i -t  ${ISTIO_INGRESS_PODNAME} -c istio-proxy -- curl -sS http://localhost:15000/runtime
```suggestion
kubectl --namespace istio-system exec -i -t  "${ISTIO_INGRESS_PODNAME}" -c istio-proxy -- curl -sS http://localhost:15000/runtime
```

2021-05-03 20:48 UTC, jacob-delgado commented
cc @brian-avery need your consent

2021-05-03 20:53 UTC, brian-avery commented
@googlebot I consent.

2021-05-03 20:57 UTC, jacob-delgado commented
@googlebot I consent.

2021-05-03 21:09 UTC, brian-avery commented
@googlebot I consent.

2021-05-03 21:10 UTC, brian-avery commented
@googlebot refresh

2021-05-03 21:45 UTC, jacob-delgado commented
@googlebot I consent.

2021-05-04 10:26 UTC, craigbox requested changes

2021-05-04 10:26 UTC, craigbox commented on content/en/boilerplates/cve-2020-007-configmap.md
> +    {{< /text >}}
There was indenting in the old version that is lost in this version.  Otherwise, it's all LGTM!

2021-05-10 21:07 UTC, istio-testing commented
@jacob-delgado: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
gencheck_istio.io | 791dec8fce2e1fca894847de53fc32774fd2b339 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9095/gencheck_istio.io/1391862013000421376) | `/test gencheck_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-15 09:23 UTC, craigbox approved these changes

2021-05-15 10:09 UTC, merged

2021-05-15 10:10 UTC, istio-testing commented
In response to a cherrypick label: #9095 failed to apply on top of branch "release-1.9":
```
Applying: Add content to the security doc around hardening based on a previously disclosed cve
Using index info to reconstruct a base tree...
M	content/en/docs/ops/best-practices/security/index.md
Falling back to patching base and 3-way merge...
Auto-merging content/en/docs/ops/best-practices/security/index.md
CONFLICT (content): Merge conflict in content/en/docs/ops/best-practices/security/index.md
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Add content to the security doc around hardening based on a previously disclosed cve
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

2021-05-15 10:10 UTC, istio-testing commented
In response to a cherrypick label: new issue created for failed cherrypick: #9753