zh-translation: zh/docs/examples/microservices-istio/enable-istio-all-microservices
istio/istio.io pull request #9130
Opened 2021-03-06 16:46 UTC by nicole-lihui

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2021-03-06 16:46 UTC, istio-testing commented
Hi @nicole-lihui. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-07 07:13 UTC, rootsongjc commented on content/zh/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
> +2.  重新部署启用 Istio 的 Bookinfo 应用。`productpage` 服务不会被重新部署，因为它已经被注入 Istio，并且它的 Pods 将不会发生变化。这次你将使用只启用单个副本的微服务。
```suggestion
2.  重新部署启用 Istio 的 Bookinfo 应用。`productpage` 服务不会被重新部署，因为它已经被注入 Istio，并且它的 Pod 将不会发生变化。这次你将使用只启用单个副本的微服务。
```

2021-03-07 07:14 UTC, rootsongjc commented on content/zh/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
> +4.  检查应用程序 Pods，并验证现在每个 Pod 的两个容器。 一个容器是微服务本身，另一个是连接到它的边车代理。
Pods 不用复数。

2021-03-07 07:14 UTC, rootsongjc commented on content/zh/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
> +[配置 Istio Ingress 网关](/docs/examples/microservices-istio/istio-ingress-gateway)。
Gateway 用英文即可，Istio 中的资源对象都保留英文词汇。

2021-03-07 10:37 UTC, rootsongjc requested changes
Need change.

2021-03-07 10:37 UTC, rootsongjc commented
/ok-to-test

2021-03-07 10:45 UTC, istio-testing commented
@nicole-lihui: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 8fb981d65634ec07e390fd4c9a37baf6d47b6b52 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9130/lint_istio.io/1368511270801641472) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-07 14:11 UTC, istio-testing commented
@nicole-lihui: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 790c1660e778ca12299af0920ca446fa0b3a70d3 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9130/lint_istio.io/1368563330280591360) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-08 14:05 UTC, kebe7jun commented on content/zh/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
> +1.  检查应用程序 Pod，并验证现在每个 Pod 的两个容器。 一个容器是微服务本身，另一个是连接到它的边车代理。
Sidecar 不需要翻译。

2021-03-10 02:10 UTC, MXuDong commented on content/zh/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
> +1.  重新部署启用 Istio 的 Bookinfo 应用。`productpage` 服务不会被重新部署，因为它已经被注入 Istio，并且它的 Pod 将不会发生变化。这次您将使用只启用单个副本的微服务。
`因为它已经被注入 Istio` 可否翻译为 `因为被 Istio 注入`

2021-03-10 02:11 UTC, MXuDong commented on content/zh/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
> +[配置 Istio Ingress Gateway](/zh/docs/examples/microservices-istio/istio-ingress-gateway)。
应该不用换行

2021-03-10 15:08 UTC, nicole-lihui commented on content/zh/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
> +1.  重新部署启用 Istio 的 Bookinfo 应用。`productpage` 服务不会被重新部署，因为它已经被注入 Istio，并且它的 Pod 将不会发生变化。这次您将使用只启用单个副本的微服务。
如果改成 ：因为被Istio注入，且它的 Pod 将不会发生改变
感觉这句话表达就没有那么准确，并且感觉有语病

2021-03-10 15:44 UTC, istio-testing commented
@nicole-lihui: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
doc.test.profile_none_istio.io | b844d37b69d3d308dd145d5836293bc62212d8d5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9130/doc.test.profile_none_istio.io/1369666912874663936) | `/test doc.test.profile_none_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-10 15:53 UTC, istio-testing commented
@nicole-lihui: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
doc.test.profile_none_istio.io | b844d37b69d3d308dd145d5836293bc62212d8d5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9130/doc.test.profile_none_istio.io/1369666912874663936) | `/test doc.test.profile_none_istio.io`
doc.test.profile_default_istio.io | b844d37b69d3d308dd145d5836293bc62212d8d5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9130/doc.test.profile_default_istio.io/1369666912811749376) | `/test doc.test.profile_default_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-11 09:41 UTC, kebe7jun approved these changes
LGTM

2021-03-11 10:19 UTC, kebe7jun commented
@rootsongjc would you please approve this PR?

2021-03-11 13:40 UTC, rootsongjc commented
Need to fix the test errors.

2021-03-12 01:43 UTC, kebe7jun commented
/retest

2021-03-12 02:00 UTC, nicole-lihui commented on content/zh/docs/examples/microservices-istio/enable-istio-all-microservices/index.md
> +1.  重新部署启用 Istio 的 Bookinfo 应用。`productpage` 服务不会被重新部署，因为它已经被注入 Istio，并且它的 Pod 将不会发生变化。这次您将使用只启用单个副本的微服务。
发现语序不对了

2021-03-12 02:41 UTC, istio-testing commented
@nicole-lihui: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
doc.test.profile_default_istio.io | b844d37b69d3d308dd145d5836293bc62212d8d5 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9130/doc.test.profile_default_istio.io/1369666912811749376) | `/test doc.test.profile_default_istio.io`
doc.test.profile_none_istio.io | d8a0c8787109127045ed57bf784e9645c3f3815a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9130/doc.test.profile_none_istio.io/1370194742561738752) | `/test doc.test.profile_none_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 02:52 UTC, istio-testing commented
@nicole-lihui: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
doc.test.profile_none_istio.io | d8a0c8787109127045ed57bf784e9645c3f3815a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9130/doc.test.profile_none_istio.io/1370194742561738752) | `/test doc.test.profile_none_istio.io`
doc.test.profile_default_istio.io | d8a0c8787109127045ed57bf784e9645c3f3815a | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9130/doc.test.profile_default_istio.io/1370194742515601408) | `/test doc.test.profile_default_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 08:12 UTC, kebe7jun commented
> Need to fix the test errors.

@rootsongjc  最近这两个测试一直是坏的，应该是 test-infra 或者运行环境出了问题，不影响这个 PR。

2021-03-24 08:54 UTC, rootsongjc approved these changes
/LGTM

2021-03-24 08:55 UTC, fleeto commented
/retest

2021-03-24 09:03 UTC, merged