zh-translation: docs/reference/config/analysis/ist0116/index.md
istio/istio.io pull request #9161
Opened 2021-03-09 11:30 UTC by MXuDong

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2021-03-09 11:30 UTC, istio-testing commented
Hi @MXuDong. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-09 11:44 UTC, SataQiu reviewed
/ok-to-test

2021-03-09 12:01 UTC, kebe7jun commented on content/zh/docs/reference/config/analysis/ist0116/index.md
> +例如具有以下 Services 的Istio网格：
```suggestion
例如包含以下 Service：
```

2021-03-09 12:01 UTC, kebe7jun commented on content/zh/docs/reference/config/analysis/ist0116/index.md
> +当一个 Deployment 的 Pods 资源的多个服务使用了相同端口但使用了不用的协议会出现该问题。
```suggestion
当一个 Deployment 的 Pod 资源的多个服务使用了相同端口但使用了不同的协议会出现该问题。
```

2021-03-09 12:38 UTC, istio-testing commented
@MXuDong: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
doc.test.profile_none_istio.io | f1e76b66974e4bc7b967b0137ab623037cd790d2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9161/doc.test.profile_none_istio.io/1369258271050829824) | `/test doc.test.profile_none_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-11 10:22 UTC, kebe7jun requested changes

2021-03-11 10:22 UTC, kebe7jun commented on content/zh/docs/reference/config/analysis/ist0116/index.md
> +当一个 Deployment 的 Pod 资源的多个服务使用了相同端口但使用了不同的协议会出现该问题。
语句不通顺啊。
```suggestion
当一个 Deployment 的 Pod 对应的多个 Service 在相同端口上定义了不同的协议会出现此消息。
```

2021-03-11 10:22 UTC, kebe7jun commented on content/zh/docs/reference/config/analysis/ist0116/index.md
> +## 示例 {#An example}
```suggestion
## 示例 {#example}
```

2021-03-11 10:22 UTC, kebe7jun commented on content/zh/docs/reference/config/analysis/ist0116/index.md
> +不可以存在两个 Service 使用不同协议监听同一 Pod 的同一端口。
```suggestion
不可以存在两个 Service 在同一个端口上使用不同协议。
```

2021-03-12 14:11 UTC, istio-testing commented
@MXuDong: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
doc.test.profile_default_istio.io | f1e76b66974e4bc7b967b0137ab623037cd790d2 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9161/doc.test.profile_default_istio.io/1369258270941777920) | `/test doc.test.profile_default_istio.io`
doc.test.profile_none_istio.io | a709c50e00e845d81173591499faa450b446762c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9161/doc.test.profile_none_istio.io/1370367819178315776) | `/test doc.test.profile_none_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 14:20 UTC, istio-testing commented
@MXuDong: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
doc.test.profile_none_istio.io | a709c50e00e845d81173591499faa450b446762c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9161/doc.test.profile_none_istio.io/1370367819178315776) | `/test doc.test.profile_none_istio.io`
doc.test.profile_default_istio.io | a709c50e00e845d81173591499faa450b446762c | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9161/doc.test.profile_default_istio.io/1370367819119595520) | `/test doc.test.profile_default_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-13 09:40 UTC, kebe7jun approved these changes
lgtm

2021-03-13 10:03 UTC, merged