zh-translation: docs/reference/config/analysis/ist0117/index.md
istio/istio.io pull request #9162
Opened 2021-03-09 11:41 UTC by MXuDong

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2021-03-09 11:41 UTC, istio-testing commented
Hi @MXuDong. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-09 11:44 UTC, SataQiu reviewed
/ok-to-test

2021-03-09 12:19 UTC, istio-testing commented
@MXuDong: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
doc.test.profile_none_istio.io | 60c92ea41fc43d9be2259fc175612f9fc58405b1 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9162/doc.test.profile_none_istio.io/1369252811916709888) | `/test doc.test.profile_none_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-09 12:57 UTC, istio-testing commented
@MXuDong: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
doc.test.profile_none_istio.io | fc87bb11498424fd9bed88919e504f2a81ca9280 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9162/doc.test.profile_none_istio.io/1369263419026313216) | `/test doc.test.profile_none_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-09 13:05 UTC, istio-testing commented
@MXuDong: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
doc.test.profile_none_istio.io | fc87bb11498424fd9bed88919e504f2a81ca9280 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9162/doc.test.profile_none_istio.io/1369263419026313216) | `/test doc.test.profile_none_istio.io`
doc.test.profile_default_istio.io | fc87bb11498424fd9bed88919e504f2a81ca9280 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9162/doc.test.profile_default_istio.io/1369263418980175872) | `/test doc.test.profile_default_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-11 10:25 UTC, kebe7jun requested changes

2021-03-11 10:25 UTC, kebe7jun commented on content/zh/docs/reference/config/analysis/ist0117/index.md
> +请查看 [Istio 要求](/zh/docs/ops/deployment/requirements/index.md)来了解更多信息。
没有 index.md 哦。

2021-03-12 14:11 UTC, istio-testing commented
@MXuDong: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
doc.test.profile_default_istio.io | fc87bb11498424fd9bed88919e504f2a81ca9280 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9162/doc.test.profile_default_istio.io/1369263418980175872) | `/test doc.test.profile_default_istio.io`
doc.test.profile_none_istio.io | 9e5abb890a59e05a09c757a54e3056a994115174 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9162/doc.test.profile_none_istio.io/1370368493278466048) | `/test doc.test.profile_none_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-12 14:23 UTC, istio-testing commented
@MXuDong: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
doc.test.profile_none_istio.io | 9e5abb890a59e05a09c757a54e3056a994115174 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9162/doc.test.profile_none_istio.io/1370368493278466048) | `/test doc.test.profile_none_istio.io`
doc.test.profile_default_istio.io | 9e5abb890a59e05a09c757a54e3056a994115174 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9162/doc.test.profile_default_istio.io/1370368493219745792) | `/test doc.test.profile_default_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-13 09:39 UTC, kebe7jun commented on content/zh/docs/reference/config/analysis/ist0117/index.md
> +当 Pods 资源没有与任何 Service 资源相关联时会出现该问题。
Pod

2021-03-15 04:20 UTC, kebe7jun approved these changes
LGTM

2021-03-15 04:21 UTC, istio-testing commented
@MXuDong: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
doc.test.profile_default_istio.io | 9e5abb890a59e05a09c757a54e3056a994115174 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9162/doc.test.profile_default_istio.io/1370368493219745792) | `/test doc.test.profile_default_istio.io`
doc.test.profile_none_istio.io | 3cacee4b29a563baa692e566fc048ebca446b6b0 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9162/doc.test.profile_none_istio.io/1371307389122252800) | `/test doc.test.profile_none_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-15 04:21 UTC, merged