zh-translation: news/releases/1.8.x/announcing-1.8.1/index.md
istio/istio.io pull request #9546
Opened 2021-04-16 11:07 UTC by orangegzx

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2021-04-20 13:50 UTC, elkan1788 requested changes
建议中文加粗部分和后面的中文不需要空格隔开

2021-04-20 13:50 UTC, elkan1788 commented on content/zh/news/releases/1.8.x/announcing-1.8.1/index.md
> +- **修复** 当将 Istio 降级到低版本时，显示不必要的警告的问题。
- **修复**当将 Istio 降级到低版本时，显示不必要的警告的问题。

2021-04-20 13:50 UTC, elkan1788 commented on content/zh/news/releases/1.8.x/announcing-1.8.1/index.md
> +- **修复** 导致 Istio 尝试验证不再支持的资源类型的错误。
- **修复**导致 Istio 尝试验证不再支持的资源类型的错误。

2021-04-21 04:58 UTC, orangegzx commented on content/zh/news/releases/1.8.x/announcing-1.8.1/index.md
> +- **修复** 当将 Istio 降级到低版本时，显示不必要的警告的问题。
个人觉得 这里区分title和内容，修复是一个title，加粗，后面是具体内容

2021-04-21 06:45 UTC, elkan1788 commented on content/zh/news/releases/1.8.x/announcing-1.8.1/index.md
> +- **修复** 当将 Istio 降级到低版本时，显示不必要的警告的问题。
@kebe7jun 关于这个格式，你怎么看？

2021-04-21 06:48 UTC, kebe7jun commented on content/zh/news/releases/1.8.x/announcing-1.8.1/index.md
> +- **修复** 当将 Istio 降级到低版本时，显示不必要的警告的问题。
我觉得，按照原样式应该没啥问题。
在这里表示着重提示。

2021-04-21 08:02 UTC, elkan1788 approved these changes

2021-04-21 08:12 UTC, kebe7jun approved these changes
lgtm

2021-04-21 08:55 UTC, merged