zh-translation:zh-translation/blog/2020/new-deployment-model/index.md
istio/istio.io pull request #9601
Opened 2021-04-25 07:59 UTC by dapengJacky

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2021-04-25 08:00 UTC, istio-testing commented
Hi @dapengJacky. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-04-25 15:09 UTC, kebe7jun commented
/ok-to-test

2021-04-26 00:21 UTC, elkan1788 requested changes
请注意数字与文字之间的空格，还有冒号的中文格式。

2021-04-26 00:21 UTC, elkan1788 commented on content/zh/blog/2020/new-deployment-model/index.md
> +根据与不同的服务网格用户和供应商合作的经验，我们认为典型的服务网格有3个关键角色:
我们认为典型的服务网格有 3 个关键角色：

2021-04-26 00:21 UTC, elkan1788 commented on content/zh/blog/2020/new-deployment-model/index.md
> +在1.7版本之前，Istio 要求控制平面在网格的一个{{< gloss "primary cluster" >}}主要集群{{< /gloss >}}中运行，导致网格操作员和网格管理员之间没有分离。 Istio 1.7引入了一个新的{{< gloss "external control plane" >}}外部控制平面{{< /gloss >}}部署模型，该模型允许网格操作人员在单独的外部集群
- 在 1.7 版本之前
- Istio 1.7 引入了一个新的

2021-04-26 00:21 UTC, elkan1788 commented on content/zh/blog/2020/new-deployment-model/index.md
> +使用 Istio 1.7中的新部署模型，可以在外部集群上运行 Istiod，与网格服务分离，如下图所示。外部控制平面集群由网格操作员拥有，而网格管理员拥有运行部署在网格中的服务的集群。网格管理员无法访问外部控制平面集群。网格操作人员可以遵循[外部 istiod 单集群逐步指南](https://github.com/istio/istio/wiki/External-Istiod-single-
使用 Istio 1.7 中的新部署模型

2021-04-26 00:21 UTC, elkan1788 commented on content/zh/blog/2020/new-deployment-model/index.md
> +网格操作员可以进一步扩展这种部署模型，从运行多个 Istio 控制平面的外部集群管理多个 Istio 控制平面:
Istio 控制平面：

2021-04-27 14:03 UTC, rootsongjc approved these changes
/lgtm

2021-04-27 15:54 UTC, merged