zh-translation:zh-translation/blog/2020/open-usage/index.md
istio/istio.io pull request #9602
Opened 2021-04-25 14:14 UTC by dapengJacky

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2021-04-25 14:14 UTC, istio-testing commented
Hi @dapengJacky. Thanks for your PR.

I'm waiting for a [istio](https://github.com/orgs/istio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/istio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=istio%2Fistio.io).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-04-25 14:36 UTC, SataQiu reviewed
/ok-to-test

2021-04-25 14:43 UTC, istio-testing commented
@dapengJacky: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | ef57f1c9fe15fa23f48d748a2998994f1562a365 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9602/lint_istio.io/1386328484183281664) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-25 14:57 UTC, istio-testing commented
@dapengJacky: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | 7d92ed570bbab11c9862b5297b648eff1df4d301 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9602/lint_istio.io/1386331919192428544) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-26 00:17 UTC, elkan1788 requested changes
请注意数字与文字之间的空格

2021-04-26 00:17 UTC, elkan1788 commented on content/zh/blog/2020/open-usage/index.md
> +在过去的12个月里，Istio 已经有了来自[100多个组织](https://istio.teststats.cncf.io/d/5/companies-table?var-period_name=Last%20year&var-metric=commits)的提交，目前有[来自14个不同公司的70名维护者](http://eng.istio.io/maintainers)。这种趋势正是项目创
- 在过去的 12 个月里
- [100 多个组织]
- [来自 14 个不同公司的 70 名维护者]

2021-04-26 00:17 UTC, elkan1788 commented on content/zh/blog/2020/open-usage/index.md
> +Open Usage Commons 专注于项目商标;它不涉及开放项目的其他方面，比如谁得到决策投票的规则。与早期的许多项目一样，Istio 的委员会也是由创始公司创立的小团队组成的。但是 Istio 已经成长和成熟（去年 Istio 是 [GitHub 中增长最快的开源项目的第4名！](https://octoverse.github.com/#fastest-growing-oss-proj
[GitHub 中增长最快的开源项目的第 4 名！]

2021-04-27 14:01 UTC, rootsongjc approved these changes
/LGTM

2021-04-27 15:54 UTC, merged