add upcoming based on steering feedback
istio/istio.io pull request #9660
Opened 2021-04-30 21:03 UTC by linsun

will also cherry pick this to istio.io.  

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2021-04-30 21:04 UTC, linsun commented
cc @craigbox @christian-posta @ericvn

2021-05-02 19:10 UTC, craigbox requested changes

2021-05-02 19:10 UTC, craigbox commented on content/en/blog/2021/discovery-selectors/index.md
> +title: "Upcoming in Istio 1.10 - use discovery selectors to configure namespaces for your Istio service mesh"
I would leave this as is in the title...

2021-05-03 01:41 UTC, linsun commented
@craigbox thanks, your feedback is resolved. PTAL! :)

2021-05-03 08:27 UTC, craigbox approved these changes
LGTM, please commit same file/s to 1.9 and/or cherrypick!

2021-05-03 09:11 UTC, merged