Add some clarification on patch tuesday
istio/istio.io pull request #9750
Opened 2021-05-14 21:26 UTC by jacob-delgado

There is no guarantee that each month will have a security release.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

2021-05-14 21:27 UTC, jacob-delgado commented
See https://github.com/istio/istio.io/pull/9719. The rest of the docs were updated.

2021-05-14 21:34 UTC, istio-testing commented
@jacob-delgado: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint_istio.io | e0cfa36c3a3390c4e292c5105d4ed8df72ac18d8 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9750/lint_istio.io/1393317101019598848) | `/test lint_istio.io`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-17 12:58 UTC, craigbox requested changes
copy edit

2021-05-17 12:58 UTC, craigbox commented on content/en/blog/2021/patch-tuesdays/index.md
> +
```suggestion
When the Product Security working group intends to ship an upcoming security patch, an
announcement will be made on [the Istio discussion
board](https://discuss.istio.io/c/announcements/5) 2 weeks prior to release. If you're
running Istio in production,  we suggest you watch the Announcements category to be
notified of such a release. If no such announcement is made there will not be a security
release for that month, barring some exceptions listed below.

```

2021-05-18 10:56 UTC, craigbox approved these changes

2021-05-18 10:57 UTC, merged

2021-05-18 10:58 UTC, istio-testing commented
In response to a cherrypick label: new pull request created: #9774